volumes:
  postgres_data:
    driver: local

services:
  postgresql:
    image: postgres:16
    shm_size: 1g
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: protocol_indexer
      POSTGRES_PASSWORD: rindexer
    ports:
      - 5432:5432
    env_file:
      - ./.env
