# !!!!!!!   DO NOT EDIT THIS FILE   !!!!!!!
# This file is machine-generated by lib/unicore/mktables from the Unicode
# database, Version 14.0.0.  Any changes made here will be lost!

# !!!!!!!   INTERNAL PERL USE ONLY   !!!!!!!
# This file is for internal use by core Perl only.  The format and even the
# name or existence of this file are subject to change without notice.  Don't
# use it directly.  Use Unicode::UCD to access the Unicode character data
# base.


return <<'END';
V80
2144
2155
2556
2558
2810
2816
3328
3329
3387
3389
7415
7416
7670
7674
8383
8384
9215
9216
11218
11219
11845
11850
12590
12591
40918
40939
66349
66352
72192
72264
72272
72324
72326
72349
72350
72355
72960
72967
72968
72970
72971
73015
73018
73019
73020
73022
73023
73032
73040
73050
94177
94178
110594
110879
110960
111356
127584
127590
128723
128725
128759
128761
129280
129292
129311
129312
129320
129328
129329
129331
129356
129357
129375
129388
129426
129432
129488
129511
183984
191457
END
