// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

/// @title SignalServiceLayout
/// @notice Storage layout documentation for SignalService
/// @dev This file is auto-generated by gen-layouts.sh. DO NOT EDIT MANUALLY.
/// @custom:security-contact security@taiko.xyz

// solhint-disable max-line-length
//   __essentialContractStorage     | uint256[251]                                       | Slot: 0    | Offset: 0    | Bytes: 8032
//   _slotsUsedByPacaya             | uint256[3]                                         | Slot: 251  | Offset: 0    | Bytes: 96  
//   _owner                         | address                                            | Slot: 254  | Offset: 0    | Bytes: 20  
//   _pendingOwner                  | address                                            | Slot: 255  | Offset: 0    | Bytes: 20  
//   _checkpoints                   | mapping(uint48 => struct SignalService.CheckpointRecord) | Slot: 256  | Offset: 0    | Bytes: 32  
//   _receivedSignals               | mapping(bytes32 => bool)                           | Slot: 257  | Offset: 0    | Bytes: 32  
//   __gap                          | uint256[44]                                        | Slot: 258  | Offset: 0    | Bytes: 1408
