# !!!!!!!   DO NOT EDIT THIS FILE   !!!!!!!
# This file is machine-generated by lib/unicore/mktables from the Unicode
# database, Version 14.0.0.  Any changes made here will be lost!

# !!!!!!!   INTERNAL PERL USE ONLY   !!!!!!!
# This file is for internal use by core Perl only.  The format and even the
# name or existence of this file are subject to change without notice.  Don't
# use it directly.  Use Unicode::UCD to access the Unicode character data
# base.


return <<'END';
V50
2385
2387
2404
2406
3046
3060
7376
7377
7378
7380
7410
7413
7416
7418
8432
8433
70400
70404
70405
70413
70415
70417
70419
70441
70442
70449
70450
70452
70453
70458
70459
70469
70471
70473
70475
70478
70480
70481
70487
70488
70493
70500
70502
70509
70512
70517
73680
73682
73683
73684
END
