// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import { Proposal0025 } from "script/layer1/proposals/Proposal0025.s.sol";
import { LibL1Addrs as L1 } from "src/layer1/mainnet/LibL1Addrs.sol";
import { LibL2Addrs as L2 } from "src/layer2/mainnet/LibL2Addrs.sol";
import { IBridge, IMessageInvocable } from "src/shared/bridge/IBridge.sol";
import { Controller } from "src/shared/governance/Controller.sol";

/// @dev Exposes the proposal's builders to `Proposal0025.t.sol` and `Proposal0025Fork.t.sol`.
/// @custom:security-contact security@taiko.xyz
contract Proposal0025Harness is Proposal0025 {
    error NotSendMessage();

    /// @dev What `BuildProposal._buildAllActions` builds and `P=0025 pnpm proposal` writes to
    /// `Proposal0025.action.md`: the L1 actions followed by one `sendMessage` carrying the L2
    /// batch. `_buildAllActions` is private to `BuildProposal`, so the wrapping is reproduced here
    /// verbatim rather than called. The committed action file is generated by the real thing and
    /// `test_actionFileMatchesTheBuiltCalldata` compares it against this, so any drift between the
    /// two fails that test instead of going unnoticed.
    /// @return The batch the DAO controller executes.
    function exposedBuildAllActions() external pure returns (Controller.Action[] memory) {
        return _allActions(_l1Deployment(), _l2Deployment());
    }

    /// @dev The same batch against injectable addresses, for rehearsals that run while a constant
    /// is still a placeholder.
    /// @param _l1 The contracts the L1 leg points at.
    /// @param _l2 The contracts the L2 leg points at.
    /// @return The batch the DAO controller executes.
    function exposedBuildAllActions(
        L1Deployment memory _l1,
        L2Deployment memory _l2
    )
        external
        pure
        returns (Controller.Action[] memory)
    {
        return _allActions(_l1, _l2);
    }

    /// @dev The message the last action of `exposedBuildAllActions` sends, as `sendMessage`
    /// receives it.
    /// @return The message.
    function exposedBuildL2Message() external pure returns (IBridge.Message memory) {
        return _l2Message(_l2Deployment());
    }

    /// @dev The same message against injectable L2 addresses.
    /// @param _l2 The contracts the L2 leg points at.
    /// @return The message.
    function exposedBuildL2Message(L2Deployment memory _l2)
        external
        pure
        returns (IBridge.Message memory)
    {
        return _l2Message(_l2);
    }

    /// @dev Decodes the message a `sendMessage` action carries.
    /// @param _data The action's calldata.
    /// @return The message.
    function decodeSendMessage(bytes calldata _data)
        external
        pure
        returns (IBridge.Message memory)
    {
        if (bytes4(_data[:4]) != IBridge.sendMessage.selector) {
            revert NotSendMessage();
        }
        return abi.decode(_data[4:], (IBridge.Message));
    }

    function exposedBuildL1Actions() external pure returns (Controller.Action[] memory) {
        return buildL1Actions();
    }

    function exposedBuildL1Actions(L1Deployment memory _l1)
        external
        pure
        returns (Controller.Action[] memory)
    {
        return buildL1Actions(_l1);
    }

    function exposedBuildL2Actions()
        external
        pure
        returns (uint64, uint32, Controller.Action[] memory)
    {
        return buildL2Actions();
    }

    function exposedBuildL2Actions(L2Deployment memory _l2)
        external
        pure
        returns (uint64, uint32, Controller.Action[] memory)
    {
        return buildL2Actions(_l2);
    }

    /// @dev Mirrors the message `BuildProposal._buildAllActions` wraps the L2 batch into.
    /// @param _l2 The contracts the L2 leg points at.
    /// @return message_ The message, as `sendMessage` receives it.
    function _l2Message(L2Deployment memory _l2)
        private
        pure
        returns (IBridge.Message memory message_)
    {
        (uint64 l2ExecutionId, uint32 l2GasLimit, Controller.Action[] memory l2Actions) =
            buildL2Actions(_l2);

        message_.srcOwner = L1.DAO_CONTROLLER;
        message_.destOwner = L2.PERMISSIONLESS_EXECUTOR;
        message_.destChainId = 167_000;
        message_.gasLimit = l2GasLimit;
        message_.to = L2.DELEGATE_CONTROLLER;
        message_.data = abi.encodeCall(
            IMessageInvocable.onMessageInvocation,
            (abi.encodePacked(l2ExecutionId, abi.encode(l2Actions)))
        );
    }

    /// @dev Mirrors `BuildProposal._buildAllActions` for a proposal with an L2 leg.
    /// @param _l1 The contracts the L1 leg points at.
    /// @param _l2 The contracts the L2 leg points at.
    /// @return actions_ The L1 actions plus the bridge message carrying the L2 batch.
    function _allActions(
        L1Deployment memory _l1,
        L2Deployment memory _l2
    )
        private
        pure
        returns (Controller.Action[] memory actions_)
    {
        Controller.Action[] memory l1Actions = buildL1Actions(_l1);
        IBridge.Message memory message = _l2Message(_l2);

        actions_ = new Controller.Action[](l1Actions.length + 1);
        for (uint256 i; i < l1Actions.length; ++i) {
            actions_[i] = l1Actions[i];
        }
        actions_[l1Actions.length] = Controller.Action({
            target: L1.BRIDGE, value: 0, data: abi.encodeCall(IBridge.sendMessage, (message))
        });
    }
}
