// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import { Proposal0024 } from "script/layer1/proposals/Proposal0024.s.sol";
import { LibL1Addrs as L1 } from "src/layer1/mainnet/LibL1Addrs.sol";
import { Controller } from "src/shared/governance/Controller.sol";

/// @dev Exposes the proposal's builders to `Proposal0024.t.sol` and `Proposal0024Fork.t.sol`.
/// @custom:security-contact security@taiko.xyz
contract Proposal0024Harness is Proposal0024 {
    error UnexpectedL2Leg();

    /// @dev What `BuildProposal._buildAllActions` builds and `P=0024 pnpm proposal` writes to
    /// `Proposal0024.action.md`: for a proposal without an L2 leg, the L1 actions alone, each
    /// checked against the zero address and the DAO controller, with no `sendMessage` appended.
    /// `_buildAllActions` is private to `BuildProposal`, so the wrapping is reproduced here rather
    /// than called. The committed action file is generated by the real thing and
    /// `test_actionFileMatchesTheBuiltCalldata` compares it against this, so any drift between the
    /// two fails that test instead of going unnoticed.
    /// @return actions_ The batch the DAO controller executes.
    function exposedBuildAllActions() external pure returns (Controller.Action[] memory actions_) {
        actions_ = buildL1Actions();

        (,, Controller.Action[] memory l2Actions) = buildL2Actions();
        require(l2Actions.length == 0, UnexpectedL2Leg());

        for (uint256 i; i < actions_.length; ++i) {
            require(actions_[i].target != address(0), TargetIsZeroAddress());
            require(actions_[i].target != L1.DAO_CONTROLLER, TargetIsDAOController());
        }
    }

    function exposedBuildL1Actions() external pure returns (Controller.Action[] memory) {
        return buildL1Actions();
    }

    function exposedBuildL1Actions(address _inboxImpl)
        external
        pure
        returns (Controller.Action[] memory)
    {
        return buildL1Actions(_inboxImpl);
    }

    function exposedBuildL2Actions()
        external
        pure
        returns (uint64, uint32, Controller.Action[] memory)
    {
        return buildL2Actions();
    }
}
