// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import { Proposal0023 } from "script/layer1/proposals/Proposal0023.s.sol";
import { LibL1Addrs as L1 } from "src/layer1/mainnet/LibL1Addrs.sol";
import { LibL2Addrs as L2 } from "src/layer2/mainnet/LibL2Addrs.sol";
import { IBridge, IMessageInvocable } from "src/shared/bridge/IBridge.sol";
import { Controller } from "src/shared/governance/Controller.sol";

/// @dev Exposes the proposal's builders to `Proposal0023.t.sol` and `Proposal0023Fork.t.sol`.
/// @custom:security-contact security@taiko.xyz
contract Proposal0023Harness is Proposal0023 {
    error NotSendMessage();

    /// @dev What `BuildProposal._buildAllActions` builds and `P=0023 pnpm proposal` writes to
    /// `Proposal0023.action.md`: the L1 actions followed by one `sendMessage` carrying the L2
    /// batch. `_buildAllActions` is private to `BuildProposal`, so the wrapping is reproduced here
    /// verbatim rather than called. The committed action file is generated by the real thing and
    /// `test_actionFileMatchesTheBuiltCalldata` compares it against this, so any drift between the
    /// two fails that test instead of going unnoticed.
    /// @return actions_ The batch the DAO controller executes.
    function exposedBuildAllActions() external pure returns (Controller.Action[] memory actions_) {
        return _allActions();
    }

    /// @dev The message the last action of `exposedBuildAllActions` sends, decoded from its
    /// calldata so it is exactly what that batch carries.
    /// @return The message, as `sendMessage` receives it.
    function exposedBuildL2Message() external view returns (IBridge.Message memory) {
        Controller.Action[] memory actions = _allActions();
        return this.decodeSendMessage(actions[actions.length - 1].data);
    }

    /// @dev Decodes the message a `sendMessage` action carries.
    /// @param _data The action's calldata.
    /// @return The message.
    function decodeSendMessage(bytes calldata _data)
        external
        pure
        returns (IBridge.Message memory)
    {
        if (bytes4(_data[:4]) != IBridge.sendMessage.selector) {
            revert NotSendMessage();
        }
        return abi.decode(_data[4:], (IBridge.Message));
    }

    function exposedBuildL1Actions() external pure returns (Controller.Action[] memory) {
        return buildL1Actions();
    }

    function exposedBuildL1Actions(L1Deployment memory _l1)
        external
        pure
        returns (Controller.Action[] memory)
    {
        return buildL1Actions(_l1);
    }

    function exposedBuildL2Actions()
        external
        pure
        returns (uint64, uint32, Controller.Action[] memory)
    {
        return buildL2Actions();
    }

    function exposedBuildL2Actions(L2Deployment memory _l2)
        external
        pure
        returns (uint64, uint32, Controller.Action[] memory)
    {
        return buildL2Actions(_l2);
    }

    /// @dev Mirrors `BuildProposal._buildAllActions` for a proposal with an L2 leg.
    /// @return actions_ The L1 actions plus the bridge message carrying the L2 batch.
    function _allActions() private pure returns (Controller.Action[] memory actions_) {
        Controller.Action[] memory l1Actions = buildL1Actions();
        (uint64 l2ExecutionId, uint32 l2GasLimit, Controller.Action[] memory l2Actions) =
            buildL2Actions();

        IBridge.Message memory message;
        message.srcOwner = L1.DAO_CONTROLLER;
        message.destOwner = L2.PERMISSIONLESS_EXECUTOR;
        message.destChainId = 167_000;
        message.gasLimit = l2GasLimit;
        message.to = L2.DELEGATE_CONTROLLER;
        message.data = abi.encodeCall(
            IMessageInvocable.onMessageInvocation,
            (abi.encodePacked(l2ExecutionId, abi.encode(l2Actions)))
        );

        actions_ = new Controller.Action[](l1Actions.length + 1);
        for (uint256 i; i < l1Actions.length; ++i) {
            actions_[i] = l1Actions[i];
        }
        actions_[l1Actions.length] = Controller.Action({
            target: L1.BRIDGE, value: 0, data: abi.encodeCall(IBridge.sendMessage, (message))
        });
    }
}
