# !!!!!!!   DO NOT EDIT THIS FILE   !!!!!!!
# This file is machine-generated by lib/unicore/mktables from the Unicode
# database, Version 14.0.0.  Any changes made here will be lost!

# !!!!!!!   INTERNAL PERL USE ONLY   !!!!!!!
# This file is for internal use by core Perl only.  The format and even the
# name or existence of this file are subject to change without notice.  Don't
# use it directly.  Use Unicode::UCD to access the Unicode character data
# base.


return <<'END';
V94
2367
2368
2382
2383
2495
2496
2503
2505
2623
2624
2751
2752
2887
2888
3014
3017
3398
3401
3545
3546
3547
3548
3903
3904
4145
4146
4228
4229
6081
6084
6681
6682
6741
6742
6766
6771
6974
6976
7078
7079
7207
7209
7220
7222
43450
43452
43567
43569
43572
43573
43755
43756
43758
43759
69809
69810
69932
69933
70068
70069
70094
70095
70369
70370
70471
70473
70710
70711
70833
70834
70841
70842
71088
71089
71096
71097
71342
71343
71462
71463
71725
71726
71989
71990
71991
71992
72146
72147
72164
72165
72881
72882
73461
73462
END
