// SPDX-License-Identifier: MIT
pragma solidity ^0.8.26;

/// @title ProverAuction2Layout
/// @notice Storage layout documentation for ProverAuction2
/// @dev This file is auto-generated by gen-layouts.sh. DO NOT EDIT MANUALLY.
/// @custom:security-contact security@taiko.xyz

// solhint-disable max-line-length
// TODO: Run `./script/gen-layouts.sh layer1` to populate storage layout.
