#![allow(dead_code, unused)]

pub mod shasta_inbox;
/// THIS IS A GENERATED FILE. DO NOT MODIFY MANUALLY.
///
/// This file was auto generated by rindexer - https://github.com/joshstevens19/rindexer
/// Any manual changes to this file will be overwritten.
mod shasta_inbox_abi_gen;
