#!/usr/bin/env node

/**
 * bridge-ui-next config generator.
 *
 * Reproduces the five SvelteKit/Vite `generate*Config` plugins
 * (scripts/vite-plugins/* in the original bridge-ui) as a single standalone
 * prebuild step. For each config it performs the identical pipeline:
 *
 *   read process.env.<VAR> (base64) -> decodeBase64ToJson -> validateJsonAgainstSchema (ajv)
 *     -> build a TS source string (same export name + same enum-reference output)
 *     -> Prettier-format -> write to src/config/generated/<name>.ts
 *
 * Export names are kept EXACTLY as the original so the `$bridgeConfig`,
 * `$chainConfig`, `$relayerConfig`, `$customToken`, `$eventIndexerConfig`
 * aliases resolve unchanged:
 *   bridgeConfig.ts        -> export const routingContractsMap: RoutingMap
 *   chainConfig.ts         -> export const chainConfig: ChainConfigMap
 *   relayerConfig.ts       -> export const configuredRelayer: RelayerConfig[]
 *   customTokenConfig.ts   -> export const customToken: Token[]
 *   eventIndexerConfig.ts  -> export const configuredEventIndexer: EventIndexerConfig[]
 *
 * SKIP_ENV_VALIDATION=true emits the same empty fallbacks as the original
 * ({} for bridge/chain, [] for relayer/customToken/eventIndexer). The
 * customToken fallback keeps the original `Token[]` typing (via a `$libs/token`
 * type-only import) so consumers like `$libs/token/tokens.ts` type-check. The
 * non-skip path reproduces the original `$libs/*` type imports + enum
 * references verbatim.
 */
import { promises as fs } from "fs";
import path from "path";
import { fileURLToPath } from "url";

import { decodeBase64ToJson } from "./utils/decodeBase64ToJson.mjs";
import { formatSourceFile } from "./utils/formatSourceFile.mjs";
import { loadEnv } from "./utils/loadEnv.mjs";
import { PluginLogger } from "./utils/PluginLogger.js";
import { validateJsonAgainstSchema } from "./utils/validateJson.mjs";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const packageRoot = path.resolve(__dirname, "..");
const schemasDir = path.join(__dirname, "config", "schemas");
const generatedDir = path.join(packageRoot, "src", "config", "generated");

await loadEnv(packageRoot);

const skip = process.env.SKIP_ENV_VALIDATION === "true";

const readSchema = async (name) =>
  JSON.parse(await fs.readFile(path.join(schemasDir, name), "utf-8"));

const header = (pluginName) =>
  `// Generated by ${pluginName} on ${new Date().toLocaleString()}\n` +
  `// WARNING: Do not change this file manually as it will be overwritten\n`;

async function writeGenerated(fileName, pluginName, body) {
  const tsFilePath = path.join(generatedDir, fileName);
  await fs.mkdir(generatedDir, { recursive: true });
  await fs.writeFile(tsFilePath, `${header(pluginName)}${body}`);
  const formatted = await formatSourceFile(tsFilePath);
  await fs.writeFile(tsFilePath, formatted);
  return tsFilePath;
}

// ---------------------------------------------------------------------------
// bridgeConfig — generateBridgeConfig
// ---------------------------------------------------------------------------
const _formatBridgeObjectToTsLiteral = (obj) => {
  const formatValue = (value) => {
    if (typeof value === "string") return `"${value}"`;
    if (typeof value === "object") return JSON.stringify(value);
    return String(value);
  };

  const entries = Object.entries(obj);
  const formattedEntries = entries.map(([key, value]) => {
    const innerEntries = Object.entries(value);
    const innerFormattedEntries = innerEntries.map(([innerKey, innerValue]) => {
      const innerInnerEntries = Object.entries(innerValue);
      const innerInnerFormattedEntries = innerInnerEntries.map(
        ([innerInnerKey, innerInnerValue]) =>
          `${innerInnerKey}: ${formatValue(innerInnerValue)}`,
      );
      return `${innerKey}: {${innerInnerFormattedEntries.join(", ")}}`;
    });
    return `${key}: {${innerFormattedEntries.join(", ")}}`;
  });

  return `{${formattedEntries.join(", ")}}`;
};

async function generateBridgeConfig() {
  const pluginName = "generateBridgeConfig";
  const logger = new PluginLogger(pluginName);
  logger.info("Plugin initialized.");

  if (skip) {
    // Empty fallback, typed as RoutingMap to match the original Vite plugin
    // (generateBridgeConfig.ts) now that $libs/bridge is ported.
    const body =
      `import type { RoutingMap } from '$libs/bridge';\n\n` +
      `export const routingContractsMap: RoutingMap = {};\n`;
    const out = await writeGenerated("bridgeConfig.ts", pluginName, body);
    logger.info(`Skipped bridge.`);
    logger.info(`Formatted config file saved to ${out}`);
    return;
  }

  if (!process.env.CONFIGURED_BRIDGES) {
    throw new Error(
      "CONFIGURED_BRIDGES is not defined in environment. Make sure to run the export step in the documentation.",
    );
  }

  const configFile = decodeBase64ToJson(process.env.CONFIGURED_BRIDGES || "");
  const schema = await readSchema("configuredBridges.schema.json");
  if (!validateJsonAgainstSchema(configFile, schema)) {
    throw new Error("encoded configuredBridges.json is not valid.");
  }

  if (
    !configFile.configuredBridges ||
    !Array.isArray(configFile.configuredBridges)
  ) {
    logger.error(
      "configuredBridges is not an array. Please check the content of the configuredBridgesConfigFile.",
    );
    throw new Error();
  }

  const routingContractsMap = {};
  configFile.configuredBridges.forEach((item) => {
    if (!routingContractsMap[item.source]) {
      routingContractsMap[item.source] = {};
    }
    routingContractsMap[item.source][item.destination] = item.addresses;
  });

  const body =
    `import type { RoutingMap } from '$libs/bridge';\n\n` +
    `export const routingContractsMap: RoutingMap = ${_formatBridgeObjectToTsLiteral(routingContractsMap)};\n`;
  const out = await writeGenerated("bridgeConfig.ts", pluginName, body);
  logger.info(`Configured ${configFile.configuredBridges.length} bridges.`);
  logger.info(`Formatted config file saved to ${out}`);
}

// ---------------------------------------------------------------------------
// chainConfig — generateChainConfig (local LayerType enum, dedupe + validate)
// ---------------------------------------------------------------------------
const LayerType = { L1: "L1", L2: "L2", L3: "L3" };

const _formatChainObjectToTsLiteral = (obj) => {
  const formatValue = (value) => {
    if (typeof value === "string") {
      if (Object.values(LayerType).includes(value)) {
        return `LayerType.${value}`;
      }
      return `"${value}"`;
    }
    if (
      typeof value === "number" ||
      typeof value === "boolean" ||
      value === null
    ) {
      return String(value);
    }
    if (Array.isArray(value)) {
      return `[${value.map(formatValue).join(", ")}]`;
    }
    if (typeof value === "object") {
      return _formatChainObjectToTsLiteral(value);
    }
    return "undefined";
  };

  if (Array.isArray(obj)) {
    return `[${obj.map(formatValue).join(", ")}]`;
  }

  const entries = Object.entries(obj);
  const formattedEntries = entries.map(
    ([key, value]) => `${key}: ${formatValue(value)}`,
  );

  return `{${formattedEntries.join(", ")}}`;
};

async function generateChainConfig() {
  const pluginName = "generateChainConfig";
  const logger = new PluginLogger(pluginName);
  logger.info("Plugin initialized.");

  const enumDecl = `enum LayerType {\n  L1 = 'L1',\n  L2 = 'L2',\n  L3 = 'L3',\n}\n`;

  if (skip) {
    const body = `export const chainConfig: Record<string, unknown> = {};\n`;
    const out = await writeGenerated("chainConfig.ts", pluginName, body);
    logger.info(`Skipped chains.`);
    logger.info(`Formatted config file saved to ${out}`);
    return;
  }

  if (!process.env.CONFIGURED_CHAINS) {
    throw new Error(
      "CONFIGURED_CHAINS is not defined in environment. Make sure to run the export step in the documentation.",
    );
  }

  const configFile = decodeBase64ToJson(process.env.CONFIGURED_CHAINS || "");
  const schema = await readSchema("configuredChains.schema.json");
  if (!validateJsonAgainstSchema(configFile, schema)) {
    throw new Error("encoded configuredChains.json is not valid.");
  }

  if (
    !configFile.configuredChains ||
    !Array.isArray(configFile.configuredChains)
  ) {
    console.error(
      "configuredChains is not an array. Please check the content of the configuredChainsConfigFile.",
    );
    throw new Error();
  }

  const chainConfig = {};
  configFile.configuredChains.forEach((item) => {
    for (const [chainIdStr, config] of Object.entries(item)) {
      const chainId = Number(chainIdStr);
      const type = config.type;

      if (Object.prototype.hasOwnProperty.call(chainConfig, chainId)) {
        logger.error(
          `Duplicate chainId ${chainId} found in configuredChains.json`,
        );
        throw new Error();
      }

      if (!Object.values(LayerType).includes(config.type)) {
        logger.error(
          `Invalid LayerType ${config.type} found for chainId ${chainId}`,
        );
        throw new Error();
      }

      chainConfig[chainId] = { ...config, type };
    }
  });

  const body =
    `import type { ChainConfigMap } from '$libs/chain';\n\n` +
    `${enumDecl}\n` +
    `export const chainConfig: ChainConfigMap = ${_formatChainObjectToTsLiteral(chainConfig)};\n`;
  const out = await writeGenerated("chainConfig.ts", pluginName, body);
  logger.info(`Configured ${Object.keys(chainConfig).length} chains.`);
  logger.info(`Formatted config file saved to ${out}`);
}

// ---------------------------------------------------------------------------
// relayerConfig — generateRelayerConfig
// ---------------------------------------------------------------------------
const _formatRelayerConfigToTsLiteral = (config) =>
  `{chainIds: [${config.chainIds ? config.chainIds.join(", ") : ""}], url: "${config.url}"}`;

const _formatRelayerArrayToTsLiteral = (relayers) =>
  `[${relayers.map(_formatRelayerConfigToTsLiteral).join(", ")}]`;

async function generateRelayerConfig() {
  const pluginName = "generateRelayerConfig";
  const logger = new PluginLogger(pluginName);
  logger.info("Plugin initialized.");

  if (skip) {
    const body = `export const configuredRelayer: { chainIds: number[]; url: string }[] = [];\n`;
    const out = await writeGenerated("relayerConfig.ts", pluginName, body);
    logger.info("Relayer config built.");
    logger.info(`Formatted config file saved to ${out}`);
    return;
  }

  if (!process.env.CONFIGURED_RELAYER) {
    throw new Error(
      "CONFIGURED_RELAYER is not defined in environment. Make sure to run the export step in the documentation.",
    );
  }

  const configFile = decodeBase64ToJson(process.env.CONFIGURED_RELAYER || "");
  const schema = await readSchema("configuredRelayer.schema.json");
  if (!validateJsonAgainstSchema(configFile, schema)) {
    throw new Error("encoded configuredRelayer.json is not valid.");
  }

  if (
    !configFile.configuredRelayer ||
    !Array.isArray(configFile.configuredRelayer)
  ) {
    console.error(
      "configuredRelayer is not an array. Please check the content of the configuredRelayerConfigFile.",
    );
    throw new Error();
  }

  const body =
    `import type { RelayerConfig } from '$libs/relayer';\n\n` +
    `export const configuredRelayer: RelayerConfig[] = ${_formatRelayerArrayToTsLiteral(configFile.configuredRelayer)};\n`;
  const out = await writeGenerated("relayerConfig.ts", pluginName, body);
  logger.info("Relayer config built.");
  logger.info(`Formatted config file saved to ${out}`);
}

// ---------------------------------------------------------------------------
// customTokenConfig — generateTokens (TokenType.<X> rewrite + value import)
// ---------------------------------------------------------------------------
const _formatTokensToTsLiteral = (tokens) => {
  const formatToken = (token) => {
    const entries = Object.entries(token);
    const formattedEntries = entries.map(([key, value]) => {
      if (key === "type" && typeof value === "string") {
        return `${key}: TokenType.${value}`;
      }
      if (typeof value === "object") {
        return `${key}: ${JSON.stringify(value)}`;
      }
      return `${key}: ${JSON.stringify(value)}`;
    });
    return `{${formattedEntries.join(", ")}}`;
  };

  return `[${tokens.map(formatToken).join(", ")}]`;
};

async function generateCustomTokenConfig() {
  const pluginName = "generateTokens";
  const logger = new PluginLogger(pluginName);
  logger.info("Plugin initialized.");

  if (skip) {
    const body =
      `import type { Token } from '$libs/token';\n\n` +
      `export const customToken: Token[] = [];\n`;
    const out = await writeGenerated("customTokenConfig.ts", pluginName, body);
    logger.info(`Skipped token.`);
    logger.info(`Formatted config file saved to ${out}`);
    return;
  }

  if (!process.env.CONFIGURED_CUSTOM_TOKENS) {
    throw new Error(
      "CONFIGURED_CUSTOM_TOKENS is not defined in environment. Make sure to run the export step in the documentation.",
    );
  }

  const configFile = decodeBase64ToJson(
    process.env.CONFIGURED_CUSTOM_TOKENS || "",
  );
  const schema = await readSchema("configuredCustomTokens.schema.json");
  if (!validateJsonAgainstSchema(configFile, schema)) {
    throw new Error("encoded generateCustomTokenConfig.json is not valid.");
  }

  const tokens = configFile;
  const body =
    `import type { Token } from '$libs/token';\n` +
    `import { TokenType } from '$libs/token';\n\n` +
    `export const customToken: Token[] = ${_formatTokensToTsLiteral(tokens)};\n`;
  const out = await writeGenerated("customTokenConfig.ts", pluginName, body);
  logger.info(`Configured ${tokens.length} tokens.`);
  logger.info(`Formatted config file saved to ${out}`);
}

// ---------------------------------------------------------------------------
// eventIndexerConfig — generateEventIndexerConfig
// ---------------------------------------------------------------------------
const _formatEventIndexerConfigToTsLiteral = (config) =>
  `{chainIds: [${config.chainIds ? config.chainIds.join(", ") : ""}], url: "${config.url}"}`;

const _formatEventIndexerArrayToTsLiteral = (indexer) =>
  `[${indexer.map(_formatEventIndexerConfigToTsLiteral).join(", ")}]`;

async function generateEventIndexerConfig() {
  const pluginName = "generateEventIndexerConfig";
  const logger = new PluginLogger(pluginName);
  logger.info("Plugin initialized.");

  if (skip) {
    const body = `export const configuredEventIndexer: { chainIds: number[]; url: string }[] = [];\n`;
    const out = await writeGenerated("eventIndexerConfig.ts", pluginName, body);
    logger.info("EventIndexer config built.");
    logger.info(`Formatted config file saved to ${out}`);
    return;
  }

  if (!process.env.CONFIGURED_EVENT_INDEXER) {
    throw new Error(
      "CONFIGURED_EVENT_INDEXER is not defined in environment. Make sure to run the export step in the documentation.",
    );
  }

  const configFile = decodeBase64ToJson(
    process.env.CONFIGURED_EVENT_INDEXER || "",
  );
  const schema = await readSchema("configuredEventIndexer.schema.json");
  if (!validateJsonAgainstSchema(configFile, schema)) {
    throw new Error("encoded configuredEventIndexer.json is not valid.");
  }

  if (
    !configFile.configuredEventIndexer ||
    !Array.isArray(configFile.configuredEventIndexer)
  ) {
    console.error(
      "configuredEventIndexer is not an array. Please check the content of the configuredEventIndexerConfigFile.",
    );
    throw new Error();
  }

  const body =
    `import type { EventIndexerConfig } from '$libs/eventIndexer';\n\n` +
    `export const configuredEventIndexer: EventIndexerConfig[] = ${_formatEventIndexerArrayToTsLiteral(
      configFile.configuredEventIndexer,
    )};\n`;
  const out = await writeGenerated("eventIndexerConfig.ts", pluginName, body);
  logger.info("EventIndexer config built.");
  logger.info(`Formatted config file saved to ${out}`);
}

// ---------------------------------------------------------------------------

async function main() {
  await generateBridgeConfig();
  await generateChainConfig();
  await generateRelayerConfig();
  await generateCustomTokenConfig();
  await generateEventIndexerConfig();
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
