name: Install pnpm dependencies
description: Reusable action to install pnpm dependencies

runs:
  using: composite
  steps:
    - name: Set up Git to use HTTPS
      shell: bash
      run: |
        git config --global url."https://github.com/".insteadOf "git@github.com:"

    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 9
        run_install: false

    - name: Install Node.js
      uses: actions/setup-node@v5
      with:
        node-version: 20
        cache: pnpm

    - name: Install dependencies
      shell: bash
      run: pnpm install
