// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import "src/shared/bridge/IBridge.sol";
import "src/shared/governance/Controller.sol";
import "src/shared/libs/LibAddress.sol";
import "src/shared/libs/LibBytes.sol";
import "src/shared/libs/LibNames.sol";

/// @title DelegateController
/// @notice This contract will be the owner of all essential contracts deployed on the L2 chain.
/// @dev Notice that when sending the message on the owner chain, the gas limit of the message must
/// not be zero, so on this chain, some EOA can help execute this transaction.
/// @dev This contract is used by Alethia Mainnet.
/// @custom:security-contact security@taiko.xyz
contract DelegateController is Controller, IMessageInvocable {
    address public immutable l2Bridge;
    address public immutable daoController;
    uint64 public immutable l1ChainId;

    error SenderNotL2Bridge();
    error InvalidTxId();
    error SenderNotL1DaoController();

    uint256[50] private __gap;

    constructor(uint64 _l1ChainId, address _l2Bridge, address _daoController) {
        l1ChainId = _l1ChainId;
        l2Bridge = _l2Bridge;
        daoController = _daoController;
    }

    function init() external initializer {
        __Essential_init(address(this));
    }

    /// @inheritdoc IMessageInvocable
    function onMessageInvocation(bytes calldata _data) external payable nonReentrant {
        require(msg.sender == l2Bridge, SenderNotL2Bridge());

        IBridge.Context memory ctx = IBridge(msg.sender).context();
        require(
            ctx.srcChainId == l1ChainId && ctx.from == daoController, SenderNotL1DaoController()
        );

        uint64 executionId = uint64(bytes8(_data[:8]));
        require(executionId == 0 || executionId == ++lastExecutionId, InvalidTxId());

        _executeActions(_data[8:]);
    }
}

// ===== STORAGE LAYOUT START =====
// This section is auto-generated by script/gen-layouts.sh. Do not edit manually.
//
// 
// ╭-----------------------------+-------------+------+--------+-------+-----------------------------------------------------------------------╮
// | Name                        | Type        | Slot | Offset | Bytes |
// +===========================================================================================================================================+
// | _initialized                | uint8       | 0    | 0      | 1     |
// |
// | _initializing               | bool        | 0    | 1      | 1     |
// |
// | __gap                       | uint256[50] | 1    | 0      | 1600  |
// |
// | _owner                      | address     | 51   | 0      | 20    |
// |
// | __gap                       | uint256[49] | 52   | 0      | 1568  |
// |
// | _pendingOwner               | address     | 101  | 0      | 20    |
// |
// | __gap                       | uint256[49] | 102  | 0      | 1568  |
// |
// | __gapFromOldAddressResolver | uint256[50] | 151  | 0      | 1600  |
// |
// | __reentry                   | uint8       | 201  | 0      | 1     |
// |
// | __paused                    | uint8       | 201  | 1      | 1     |
// |
// | __gap                       | uint256[49] | 202  | 0      | 1568  |
// |
// | __reserved0                 | uint256     | 251  | 0      | 32    |
// |
// | lastExecutionId             | uint64      | 252  | 0      | 8     |
// |
// | __reserved1                 | address     | 252  | 8      | 20    |
// |
// | __gap                       | uint256[48] | 253  | 0      | 1536  |
// |
// | __gap                       | uint256[50] | 301  | 0      | 1600  |
// ╰-----------------------------+-------------+------+--------+-------+-----------------------------------------------------------------------╯
// 
//
// ===== STORAGE LAYOUT END =====
