#!/bin/bash

# Storage Layout Generation Script for Optaiko
#
# Generates storage layout as a separate *Layout.sol file.
#
# Usage: ./gen-layouts.sh
#
# Creates Optaiko_Layout.sol with storage layout as comments.
# Re-running the script replaces the old layout file with an updated one.

set -euo pipefail

# Contract to generate layout for
CONTRACT="contracts/Optaiko4.sol:Optaiko4"
FILE_PATH="${CONTRACT%%:*}"  # Extract path before colon
CONTRACT_NAME="${CONTRACT##*:}"  # Extract contract name after colon

echo "Generating Optaiko4 storage layout..."

# Check if contract file exists
if [ ! -f "$FILE_PATH" ]; then
    echo "❌ Failed: ${CONTRACT} (file not found)"
    exit 1
fi

# Derive layout file path: Optaiko.sol -> Optaiko_Layout.sol
DIR_PATH="${FILE_PATH%/*}"
BASE_NAME="${FILE_PATH##*/}"
BASE_NAME_NO_EXT="${BASE_NAME%.sol}"
LAYOUT_FILE_PATH="${DIR_PATH}/${BASE_NAME_NO_EXT}_Layout.sol"

# Generate storage layout
echo "Running forge inspect..."
LAYOUT_OUTPUT=$(FORGE_DISPLAY=plain forge inspect "${CONTRACT}" storagelayout 2>&1) || {
    echo "❌ Failed: ${CONTRACT} (forge inspect failed)"
    echo "$LAYOUT_OUTPUT"
    exit 1
}

# Parse layout table: extract data rows with pipes, skip headers and borders
LAYOUT_COMMENTS=$(echo "$LAYOUT_OUTPUT" | awk -F'|' '
    NF >= 6 && /\|/ {
        # Trim whitespace from each field
        for (i=1; i<=NF; i++) gsub(/^[ \t]+|[ \t]+$/, "", $i);
        name=$2; type=$3; slot=$4; offset=$5; bytes=$6;

        # Skip headers, empty rows, and border characters
        if (name == "Name" || name == "" || slot == "Slot" || name ~ /^[─═╭╰│┤┐└┴┬├┼+\-]+$/) next;

        printf "  %-30s | %-50s | Slot: %-4s | Offset: %-4s | Bytes: %-4s\n", name, type, slot, offset, bytes;
    }
' | sed 's/^/\/\/ /')

if [ -z "$LAYOUT_COMMENTS" ]; then
    echo "❌ Failed: ${CONTRACT} (no layout data)"
    exit 1
fi

# Create/overwrite the layout file
cat > "$LAYOUT_FILE_PATH" <<EOF
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.26;

/// @title ${CONTRACT_NAME}Layout
/// @notice Storage layout documentation for ${CONTRACT_NAME}
/// @dev This file is auto-generated by gen-layouts.sh. DO NOT EDIT MANUALLY.
/// @custom:security-contact security@optaiko.xyz

// solhint-disable max-line-length
${LAYOUT_COMMENTS}
EOF

echo "✅ Updated: ${LAYOUT_FILE_PATH}"
echo ""
echo "=========================================="
echo "✅ Storage layout generated successfully!"
echo "=========================================="
