[package]
name = "monitor"
version = "0.1.0"
edition = "2024"

[dependencies]
eyre = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true }
tracing.workspace = true
alloy.workspace = true
futures-util.workspace = true
bindings.workspace = true
metrics.workspace = true
beacon.workspace = true
utils.workspace = true
