// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

/// @title LookaheadStoreLayout
/// @notice Storage layout documentation for LookaheadStore
/// @dev This file is auto-generated by gen-layouts.sh. DO NOT EDIT MANUALLY.
/// @custom:security-contact security@taiko.xyz

// solhint-disable max-line-length
//   overseers                      | mapping(address => bool)                           | Slot: 0    | Offset: 0    | Bytes: 32  
//   blacklist                      | mapping(bytes32 => struct IBlacklist.BlacklistTimestamps) | Slot: 1    | Offset: 0    | Bytes: 32  
//   __gap                          | uint256[48]                                        | Slot: 2    | Offset: 0    | Bytes: 1536
//   _initialized                   | uint8                                              | Slot: 50   | Offset: 0    | Bytes: 1   
//   _initializing                  | bool                                               | Slot: 50   | Offset: 1    | Bytes: 1   
//   __gap                          | uint256[50]                                        | Slot: 51   | Offset: 0    | Bytes: 1600
//   _owner                         | address                                            | Slot: 101  | Offset: 0    | Bytes: 20  
//   __gap                          | uint256[49]                                        | Slot: 102  | Offset: 0    | Bytes: 1568
//   _pendingOwner                  | address                                            | Slot: 151  | Offset: 0    | Bytes: 20  
//   __gap                          | uint256[49]                                        | Slot: 152  | Offset: 0    | Bytes: 1568
//   __gapFromOldAddressResolver    | uint256[50]                                        | Slot: 201  | Offset: 0    | Bytes: 1600
//   __reentry                      | uint8                                              | Slot: 251  | Offset: 0    | Bytes: 1   
//   __paused                       | uint8                                              | Slot: 251  | Offset: 1    | Bytes: 1   
//   __gap                          | uint256[49]                                        | Slot: 252  | Offset: 0    | Bytes: 1568
//   lookahead                      | mapping(uint256 => struct ILookaheadStore.LookaheadHash) | Slot: 301  | Offset: 0    | Bytes: 32  
//   __gap                          | uint256[49]                                        | Slot: 302  | Offset: 0    | Bytes: 1568
