// SPDX-License-Identifier: MIT
pragma solidity ^0.8.26;

/// @title PreconfWhitelistLayout
/// @notice Storage layout documentation for PreconfWhitelist
/// @dev This file is auto-generated by gen-layouts.sh. DO NOT EDIT MANUALLY.
/// @custom:security-contact security@taiko.xyz

// solhint-disable max-line-length
//   _owner                         | address                                            | Slot: 0    | Offset: 0    | Bytes: 20  
//   operators                      | mapping(address => struct PreconfWhitelist.OperatorInfo) | Slot: 1    | Offset: 0    | Bytes: 32  
//   operatorMapping                | mapping(uint256 => address)                        | Slot: 2    | Offset: 0    | Bytes: 32  
//   operatorCount                  | uint8                                              | Slot: 3    | Offset: 0    | Bytes: 1   
//   latestActivationEpoch          | uint32                                             | Slot: 3    | Offset: 1    | Bytes: 4   
//   ejecters                       | mapping(address => bool)                           | Slot: 4    | Offset: 0    | Bytes: 32  
