apiVersion: v2
name: erc8004-webserver
description: ERC-8004 Off-Chain Storage Server Helm Chart for Taiko
type: application
version: 1.0.0
appVersion: "1.0.0"
home: https://github.com/taikoxyz/taiko-mono
sources:
  - https://github.com/taikoxyz/taiko-mono
maintainers:
  - name: Taiko Labs
    email: security@taiko.xyz
keywords:
  - erc8004
  - blockchain
  - ethereum
  - taiko
  - agents
annotations:
  category: Blockchain Infrastructure