# Production values for erc8004-webserver
replicaCount: 5

image:
  repository: registry.taiko.xyz/erc8004-server
  tag: "v1.0.0"
  pullPolicy: Always

imagePullSecrets:
  - name: taiko-registry-secret

resources:
  limits:
    cpu: 2000m
    memory: 2Gi
  requests:
    cpu: 1000m
    memory: 1Gi

autoscaling:
  enabled: true
  minReplicas: 5
  maxReplicas: 20
  targetCPUUtilizationPercentage: 60
  targetMemoryUtilizationPercentage: 70

config:
  server:
    domain: "agent.taiko.xyz"
    environment: "production"
  
  blockchain:
    web3Provider: "https://rpc.mainnet.taiko.xyz"
    chainId: 167000
    contractAddress: "0x..." # Set actual contract address
  
  monitoring:
    logLevel: "INFO"

postgresql:
  auth:
    postgresPassword: "CHANGE_IN_PRODUCTION"
    username: "agent_user"
    password: "CHANGE_IN_PRODUCTION"
  primary:
    persistence:
      size: 100Gi
      storageClass: "fast-ssd"
    resources:
      limits:
        cpu: 2000m
        memory: 4Gi
      requests:
        cpu: 1000m
        memory: 2Gi

redis:
  auth:
    password: "CHANGE_IN_PRODUCTION" 
  master:
    persistence:
      size: 50Gi
      storageClass: "fast-ssd"
    resources:
      limits:
        cpu: 1000m
        memory: 2Gi
      requests:
        cpu: 500m
        memory: 1Gi

persistence:
  size: 100Gi
  storageClass: "fast-ssd"

ingress:
  hosts:
    - host: agent.taiko.xyz
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: taiko-agent-tls
      hosts:
        - agent.taiko.xyz

secrets:
  secretKey: "CHANGE_IN_PRODUCTION"
  databaseUrl: "postgresql+asyncpg://agent_user:CHANGE_IN_PRODUCTION@erc8004-webserver-postgresql:5432/agent_db"
  redisUrl: "redis://:CHANGE_IN_PRODUCTION@erc8004-webserver-redis-master:6379"