# !!!!!!!   DO NOT EDIT THIS FILE   !!!!!!!
# This file is machine-generated by lib/unicore/mktables from the Unicode
# database, Version 14.0.0.  Any changes made here will be lost!

# !!!!!!!   INTERNAL PERL USE ONLY   !!!!!!!
# This file is for internal use by core Perl only.  The format and even the
# name or existence of this file are subject to change without notice.  Don't
# use it directly.  Use Unicode::UCD to access the Unicode character data
# base.


return <<'END';
V40
11904
11930
11931
12020
12032
12246
12293
12294
12295
12296
12321
12330
12344
12348
13312
19904
19968
40960
63744
64110
64112
64218
94178
94180
94192
94194
131072
173792
173824
177977
177984
178206
178208
183970
183984
191457
194560
195102
196608
201547
END
