// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import "./EssentialContract.sol";
import "./ResolverBase.sol";

/// @title DefaultResolver
/// @notice Storage-based address resolver.
/// @custom:security-contact security@taiko.xyz
contract DefaultResolver is EssentialContract, ResolverBase {
    /// @dev Mapping of chainId to mapping of name to address.
    mapping(uint256 chainId => mapping(bytes32 name => address addr)) private __addresses;

    uint256[49] private __gap;

    /// @notice Emitted when an address is registered.
    /// @param chainId The chainId for the address mapping.
    /// @param name The name for the address mapping.
    /// @param newAddress The new address.
    /// @param oldAddress The old address.
    event AddressRegistered(
        uint256 indexed chainId, bytes32 indexed name, address newAddress, address oldAddress
    );

    /// @notice Initializes the contract.
    /// @param _owner The owner of this contract.
    function init(address _owner) external initializer {
        __Essential_init(_owner);
    }

    /// @notice Registers an address for a specific chainId-name pair.
    /// @param _chainId The chainId to which the address will be mapped.
    /// @param _name The name to which the address will be mapped.
    /// @param _newAddress The Ethereum address to be mapped.
    function registerAddress(
        uint256 _chainId,
        bytes32 _name,
        address _newAddress
    )
        external
        virtual
        onlyOwner
    {
        address oldAddress = __addresses[_chainId][_name];
        __addresses[_chainId][_name] = _newAddress;
        emit AddressRegistered(_chainId, _name, _newAddress, oldAddress);
    }

    /// @notice Returns the address of this contract.
    /// @return The address of this contract.
    function resolver() public view override returns (address) {
        return address(this);
    }

    function getAddress(
        uint256 _chainId,
        bytes32 _name
    )
        internal
        view
        override
        returns (address)
    {
        return __addresses[_chainId][_name];
    }

    function _authorizePause(address, bool) internal pure override notImplemented { }
}







// ===== STORAGE LAYOUT START =====
// This section is auto-generated by script/gen-layouts.sh. Do not edit manually.
//
//   _initialized                   | uint8                                              | Slot: 0    | Offset: 0    | Bytes: 1   
//   _initializing                  | bool                                               | Slot: 0    | Offset: 1    | Bytes: 1   
//   __gap                          | uint256[50]                                        | Slot: 1    | Offset: 0    | Bytes: 1600
//   _owner                         | address                                            | Slot: 51   | Offset: 0    | Bytes: 20  
//   __gap                          | uint256[49]                                        | Slot: 52   | Offset: 0    | Bytes: 1568
//   _pendingOwner                  | address                                            | Slot: 101  | Offset: 0    | Bytes: 20  
//   __gap                          | uint256[49]                                        | Slot: 102  | Offset: 0    | Bytes: 1568
//   __gapFromOldAddressResolver    | uint256[50]                                        | Slot: 151  | Offset: 0    | Bytes: 1600
//   __reentry                      | uint8                                              | Slot: 201  | Offset: 0    | Bytes: 1   
//   __paused                       | uint8                                              | Slot: 201  | Offset: 1    | Bytes: 1   
//   __gap                          | uint256[49]                                        | Slot: 202  | Offset: 0    | Bytes: 1568
//   __addresses                    | mapping(uint256 => mapping(bytes32 => address))    | Slot: 251  | Offset: 0    | Bytes: 32  
//   __gap                          | uint256[49]                                        | Slot: 252  | Offset: 0    | Bytes: 1568
//
// ===== STORAGE LAYOUT END =====
