module.exports = {
  content: ['./src/**/*.{html,js,svelte,ts}'],
  plugins: [require('daisyui')],
  darkMode: ['class', '[data-theme="dark"]'],
  theme: {
    extend: {
      colors: {
        'dark-1': 'var(--color-dark-1)',
        'dark-2': 'var(--color-dark-2)',
        'dark-3': 'var(--color-dark-3)',
        'dark-4': 'var(--color-dark-4)',
        'dark-5': 'var(--color-dark-5)',
        'dark-6': 'var(--color-dark-6)',
        tabs: 'var(--tabs)',
      },
      keyframes: {
        rise: {
          '0%': { position: 'absolute', bottom: '-10px' },
          // '100%': { position: 'static' },
        },
      },
      animation: {
        rise: 'rise 0.5s ease-in-out',
      },
    },
  },
  daisyui: {
    styled: true,
    base: true,
    utils: true,
    logs: true,
    rtl: false,
    prefix: '',
    darkTheme: 'dark',
    themes: [
      {
        dark: {
          ...require('daisyui/colors/themes')['[data-theme=black]'],
          primary: '#242424',
          secondary: '#181818',
          accent: '#E81899',
          'accent-focus': '#E81899',
          'accent-content': '#F3F3F3',
          neutral: '#242424',
          'base-100': '#10151B',
          'base-300': '#242424',
          info: '#373737',
          success: '#008000',
          warning: '#FFFF00',
          error: '#FF0000',
          '--color-dark-1': '#000000',
          '--color-dark-2': '#000000',
          '--color-dark-3': '#0F0F0F',
          '--color-dark-4': '#242424',
          '--color-dark-5': '#373737',
          '--color-dark-6': '#4F4F4F',
          '--rounded-btn': '.5rem',
          '--rounded-box': '.5rem',
          '--btn-text-case': 'capitalize',
          '--tabs': '#1E2026',
        },
        light: {
          ...require('daisyui/colors/themes')['[data-theme=light]'],
          accent: '#E81899',
          'accent-focus': '#E81899',
          'accent-content': '#F3F3F3',
          neutral: '#d4d4d4',
          'neutral-focus': '#a3a3a3',
          'neutral-content': '#181818',
          'base-100': '#F3F3F3',
          'base-300': '#d4d4d4',
          info: '#373737',
          success: '#008000',
          warning: '#FFFF00',
          error: '#FF0000',
          '--color-dark-1': '#000000',
          '--color-dark-2': '#FFFFFF',
          '--color-dark-3': '#FAFAFA',
          '--color-dark-4': '#242424',
          '--color-dark-5': '#CDCDCD',
          '--color-dark-6': '#4F4F4F',
          '--rounded-btn': '.5rem',
          '--rounded-box': '.5rem',
          '--btn-text-case': 'capitalize',
          '--tabs': '#F3F3F3',
        },
      },
    ],
  },
};
