[package]
name = "bindings"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
alloy = { workspace = true, features = ["contract", "sol-types", "providers"] }