[package]
name = "event-indexer"
version = "0.1.0"
edition = "2024"

[dependencies]
alloy = { workspace = true }
alloy-contract = { workspace = true }
alloy-primitives = { workspace = true, default-features = false }
alloy-provider = { workspace = true }
alloy-rpc-types = { workspace = true }
alloy-sol-macro = { workspace = true, features = ["json"] }
alloy-sol-types = { workspace = true }
anyhow = { workspace = true }
async-trait = { workspace = true }
bindings = { path = "../bindings" }
dashmap = { workspace = true }
event-scanner = { workspace = true }
rpc = { path = "../rpc" }
tokio = { workspace = true }
tokio-stream = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
alloy-eips = { workspace = true }
alloy-json-rpc = { workspace = true }
alloy-signer-local = { workspace = true }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
