[package]
name = "event-indexer"
version.workspace = true
edition.workspace = true

[dependencies]
async-trait = { workspace = true }
# async
tokio = { workspace = true }
tokio-retry = { workspace = true }
tokio-stream = { workspace = true }

# observability
metrics = { workspace = true }
tracing = { workspace = true }

# ethereum
alloy = { workspace = true }
alloy-contract = { workspace = true }
alloy-json-rpc = { workspace = true, default-features = false }
alloy-primitives = { workspace = true, default-features = false }
alloy-provider = { workspace = true }
alloy-rpc-types = { workspace = true }
alloy-sol-macro = { workspace = true, features = ["json"] }
alloy-sol-types = { workspace = true }

# taiko
bindings = { path = "../bindings" }
event-scanner = { workspace = true }
rpc = { path = "../rpc" }

# types
anyhow = { workspace = true }
dashmap = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
# observability
tracing-subscriber = { workspace = true, features = ["env-filter"] }

# ethereum
alloy-eips = { workspace = true }
alloy-json-rpc = { workspace = true }
alloy-signer-local = { workspace = true }
