/* eslint-disable no-console */
import { promises as fs } from 'fs';
import path from 'path';
import * as prettier from 'prettier';
import { Project, SourceFile, VariableDeclarationKind } from 'ts-morph';

import { Logger } from "./utils/Logger";

const pluginName = 'generateRelayerConfig';
const logger = new Logger(pluginName);
const currentDir = path.resolve(new URL(import.meta.url).pathname);

// Todo: make paths and names configurable via .env?
const outputPath = path.join(path.join(path.dirname(currentDir)), '../src/generated/relayerConfig.ts');


type RelayerConfig = {
    "chainId": number[],
    "url": string,
}


export function generateRelayerConfig() {
    return {
        name: pluginName,
        async buildStart() {
            logger.info('Plugin initialized.');
            const project = new Project();

            // Path to where you want to save the generated TypeScript file
            const tsFilePath = path.resolve(outputPath);

            // Notification and warning message
            const timestamp = new Date().toLocaleString();
            const notification = `// Generated by ${pluginName} on ${timestamp}`;
            const warning = `// WARNING: Do not change this file manually as it will be overwritten`;

            // Create the TypeScript content
            let sourceFile = project.createSourceFile(tsFilePath, `${notification}\n${warning}\n`, { overwrite: true });

            // Create the TypeScript content

            sourceFile = await storeTypesAndEnums(sourceFile);
            sourceFile = await buildRelayerConfig(sourceFile);

            // Save the file
            await sourceFile.saveSync();
            logger.info(`Generated config file`);

            const generatedCode = await fs.readFile(tsFilePath, 'utf-8');

            logger.info(`Formatting...`);
            // Format the code using Prettier
            const formattedCode = await prettier.format(generatedCode, { parser: 'typescript' });

            // Write the formatted code back to the file
            await fs.writeFile(tsFilePath, formattedCode);
            logger.info(`Formatted config file saved to ${tsFilePath}`);
        },
    };
}

async function storeTypesAndEnums(sourceFile: SourceFile) {
    logger.info(`Storing types and enums...`);
    // todo
    return sourceFile
}

async function buildRelayerConfig(sourceFile: SourceFile) {
    logger.info('Building relayer config...');
    // todo
    return sourceFile
}