/* eslint-disable no-console */
import { promises as fs } from 'fs';
import path from 'path';
import * as prettier from 'prettier';
import { Project, SourceFile, VariableDeclarationKind } from 'ts-morph';

import { Logger } from './utils/Logger';

const currentDir = path.resolve(new URL(import.meta.url).pathname);

// Todo: make paths and names configurable via .env?
const outputPath = path.join(path.join(path.dirname(currentDir)), '../src/generated/chainConfig.ts');

const configuredChainsConfigFile = path.join(path.dirname(currentDir), '../config', 'configuredChains.json');

enum LayerType {
  L1 = 'L1',
  L2 = 'L2',
  L3 = 'L3',
}

// Make sure all types match the ones in the functions below when making changes
type Urls = {
  rpc: string;
  explorer: string;
};

type ChainConfig = {
  name: string;
  urls: Urls;
  icon: string;
  type: LayerType;
};

type ChainConfigMap = Record<number, ChainConfig>;

type ConfiguredChains = {
  configuredChains: Array<Record<string, Omit<ChainConfig, 'chainId'>>>;
};

const pluginName = 'generateChainConfig';
const logger = new Logger(pluginName);

export function generateChainConfig() {
  return {
    name: pluginName,
    async buildStart() {
      logger.info('Plugin initialized.');
      const project = new Project();

      // Path to where you want to save the generated TypeScript file
      const tsFilePath = path.resolve(outputPath);

      // Notification and warning message
      const timestamp = new Date().toLocaleString();
      const notification = `// Generated by ${pluginName} on ${timestamp}`;
      const warning = `// WARNING: Do not change this file manually as it will be overwritten`;

      // Create the TypeScript content
      let sourceFile = project.createSourceFile(tsFilePath, `${notification}\n${warning}\n`, { overwrite: true });

      // Create the TypeScript content

      sourceFile = await storeTypesAndEnums(sourceFile);
      sourceFile = await buildChainConfig(sourceFile);

      // Save the file
      await sourceFile.saveSync();
      logger.info(`Generated config file`);

      const generatedCode = await fs.readFile(tsFilePath, 'utf-8');

      logger.info(`Formatting...`);
      // Format the code using Prettier
      const formattedCode = await prettier.format(generatedCode, { parser: 'typescript' });

      // Write the formatted code back to the file
      await fs.writeFile(tsFilePath, formattedCode);
      logger.info(`Formatted config file saved to ${tsFilePath}`);
    },
  };
}

async function storeTypesAndEnums(sourceFile: SourceFile) {
  logger.info(`Storing types and enums...`);
  // Urls
  sourceFile.addTypeAlias({
    name: 'Urls',
    isExported: false,
    type: `{
      rpc: string;
      explorer: string;
    }`,
  });

  // LayerType
  sourceFile.addEnum({
    name: 'LayerType',
    isExported: false,
    members: [
      { name: 'L1', value: 'L1' },
      { name: 'L2', value: 'L2' },
      { name: 'L3', value: 'L3' },
    ],
  });

  // ChainConfig
  sourceFile.addTypeAlias({
    name: 'ChainConfig',
    isExported: true,
    type: `{
      name: string;
      urls: Urls;
      icon: string;
      type: LayerType;
    }`,
  });


  // ChainConfigMap
  sourceFile.addTypeAlias({
    name: 'ChainConfigMap',
    isExported: true,
    type: `Record<number, ChainConfig>`,
  });

  logger.info('Types and enums stored.');
  return sourceFile;
}

async function buildChainConfig(sourceFile: SourceFile) {
  const chainConfig: ChainConfigMap = {};

  const chainsJsonContent = await fs.readFile(configuredChainsConfigFile, 'utf-8');
  const chains: ConfiguredChains = JSON.parse(chainsJsonContent);

  if (!chains.configuredChains || !Array.isArray(chains.configuredChains)) {
    console.error('configuredChains is not an array. Please check the content of the configuredChainsConfigFile.');
    throw new Error();
  }

  chains.configuredChains.forEach((item: Record<string, ChainConfig>) => {
    for (const [chainIdStr, config] of Object.entries(item)) {
      const chainId = Number(chainIdStr);
      const type = config.type as LayerType;

      // Check for duplicates
      if (Object.prototype.hasOwnProperty.call(chainConfig, chainId)) {
        logger.error(`Duplicate chainId ${chainId} found in configuredChains.json`);
        throw new Error();
      }

      // Validate LayerType
      if (!Object.values(LayerType).includes(config.type)) {
        logger.error(`Invalid LayerType ${config.type} found for chainId ${chainId}`);
        throw new Error();
      }

      chainConfig[chainId] = { ...config, type };
    }
  });

  // Add chainConfig variable to sourceFile
  sourceFile.addVariableStatement({
    declarationKind: VariableDeclarationKind.Const,
    declarations: [
      {
        name: 'chainConfig',
        type: 'ChainConfigMap',
        initializer: _formatObjectToTsLiteral(chainConfig),
      },
    ],
    isExported: true,
  });

  logger.info(`Configured ${Object.keys(chainConfig).length} chains.`);
  return sourceFile;
}


const _formatObjectToTsLiteral = (obj: ChainConfigMap): string => {
  const formatValue = (value: any): string => {
    if (typeof value === 'string') {
      if (Object.values(LayerType).includes(value as LayerType)) {
        return `LayerType.${value}`;
      }
      return `"${value}"`;
    }
    if (typeof value === 'number' || typeof value === 'boolean' || value === null) {
      return String(value);
    }
    if (Array.isArray(value)) {
      return `[${value.map(formatValue).join(', ')}]`;
    }
    if (typeof value === 'object') {
      return _formatObjectToTsLiteral(value);
    }
    return 'undefined';
  };

  if (Array.isArray(obj)) {
    return `[${obj.map(formatValue).join(', ')}]`;
  }

  const entries = Object.entries(obj);
  const formattedEntries = entries.map(([key, value]) => `${key}: ${formatValue(value)}`);

  return `{${formattedEntries.join(', ')}}`;
};
