// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

/// @title BridgedERC721Layout
/// @notice Storage layout documentation for BridgedERC721
/// @dev This file is auto-generated by gen-layouts.sh. DO NOT EDIT MANUALLY.
/// @custom:security-contact security@taiko.xyz

// solhint-disable max-line-length
//   _initialized                   | uint8                                              | Slot: 0    | Offset: 0    | Bytes: 1   
//   _initializing                  | bool                                               | Slot: 0    | Offset: 1    | Bytes: 1   
//   __gap                          | uint256[50]                                        | Slot: 1    | Offset: 0    | Bytes: 1600
//   _owner                         | address                                            | Slot: 51   | Offset: 0    | Bytes: 20  
//   __gap                          | uint256[49]                                        | Slot: 52   | Offset: 0    | Bytes: 1568
//   _pendingOwner                  | address                                            | Slot: 101  | Offset: 0    | Bytes: 20  
//   __gap                          | uint256[49]                                        | Slot: 102  | Offset: 0    | Bytes: 1568
//   __gapFromOldAddressResolver    | uint256[50]                                        | Slot: 151  | Offset: 0    | Bytes: 1600
//   __reentry                      | uint8                                              | Slot: 201  | Offset: 0    | Bytes: 1   
//   __paused                       | uint8                                              | Slot: 201  | Offset: 1    | Bytes: 1   
//   __gap                          | uint256[49]                                        | Slot: 202  | Offset: 0    | Bytes: 1568
//   __gap                          | uint256[50]                                        | Slot: 251  | Offset: 0    | Bytes: 1600
//   _name                          | string                                             | Slot: 301  | Offset: 0    | Bytes: 32  
//   _symbol                        | string                                             | Slot: 302  | Offset: 0    | Bytes: 32  
//   _owners                        | mapping(uint256 => address)                        | Slot: 303  | Offset: 0    | Bytes: 32  
//   _balances                      | mapping(address => uint256)                        | Slot: 304  | Offset: 0    | Bytes: 32  
//   _tokenApprovals                | mapping(uint256 => address)                        | Slot: 305  | Offset: 0    | Bytes: 32  
//   _operatorApprovals             | mapping(address => mapping(address => bool))       | Slot: 306  | Offset: 0    | Bytes: 32  
//   __gap                          | uint256[44]                                        | Slot: 307  | Offset: 0    | Bytes: 1408
//   srcToken                       | address                                            | Slot: 351  | Offset: 0    | Bytes: 20  
//   srcChainId                     | uint256                                            | Slot: 352  | Offset: 0    | Bytes: 32  
//   __gap                          | uint256[48]                                        | Slot: 353  | Offset: 0    | Bytes: 1536
