// SPDX-License-Identifier: MIT
pragma solidity ^0.8.26;

/// @title BridgedERC20V3Layout
/// @notice Storage layout documentation for BridgedERC20V3
/// @dev This file will be auto-generated by gen-layouts.sh. DO NOT EDIT MANUALLY.
/// @custom:security-contact security@taiko.xyz

// solhint-disable max-line-length
// Storage layout extends BridgedERC20V2:
//   ... (inherited from BridgedERC20V2)
//   _nonces                        | mapping(address => struct CountersUpgradeable.Counter) | Slot: 403  | Offset: 0    | Bytes: 32
//   __gap                          | uint256[49]                                        | Slot: 404  | Offset: 0    | Bytes: 1568
// NEW in V3:
//   _authorizationStates           | mapping(address => mapping(bytes32 => bool))       | Slot: 453  | Offset: 0    | Bytes: 32
//   __gap                          | uint256[48]                                        | Slot: 454  | Offset: 0    | Bytes: 1536
