// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

/// @title ERC20VaultLayout
/// @notice Storage layout documentation for ERC20Vault
/// @dev This file is auto-generated by gen-layouts.sh. DO NOT EDIT MANUALLY.
/// @custom:security-contact security@taiko.xyz

// solhint-disable max-line-length
//   _initialized                   | uint8                                              | Slot: 0    | Offset: 0    | Bytes: 1   
//   _initializing                  | bool                                               | Slot: 0    | Offset: 1    | Bytes: 1   
//   __gap                          | uint256[50]                                        | Slot: 1    | Offset: 0    | Bytes: 1600
//   _owner                         | address                                            | Slot: 51   | Offset: 0    | Bytes: 20  
//   __gap                          | uint256[49]                                        | Slot: 52   | Offset: 0    | Bytes: 1568
//   _pendingOwner                  | address                                            | Slot: 101  | Offset: 0    | Bytes: 20  
//   __gap                          | uint256[49]                                        | Slot: 102  | Offset: 0    | Bytes: 1568
//   __gapFromOldAddressResolver    | uint256[50]                                        | Slot: 151  | Offset: 0    | Bytes: 1600
//   __reentry                      | uint8                                              | Slot: 201  | Offset: 0    | Bytes: 1   
//   __paused                       | uint8                                              | Slot: 201  | Offset: 1    | Bytes: 1   
//   __gap                          | uint256[49]                                        | Slot: 202  | Offset: 0    | Bytes: 1568
//   __gap                          | uint256[50]                                        | Slot: 251  | Offset: 0    | Bytes: 1600
//   bridgedToCanonical             | mapping(address => struct ERC20Vault.CanonicalERC20) | Slot: 301  | Offset: 0    | Bytes: 32  
//   canonicalToBridged             | mapping(uint256 => mapping(address => address))    | Slot: 302  | Offset: 0    | Bytes: 32  
//   btokenDenylist                 | mapping(address => bool)                           | Slot: 303  | Offset: 0    | Bytes: 32  
//   lastMigrationStart             | mapping(uint256 => mapping(address => uint256))    | Slot: 304  | Offset: 0    | Bytes: 32  
//   __gap                          | uint256[46]                                        | Slot: 305  | Offset: 0    | Bytes: 1472
