// SPDX-License-Identifier: MIT
pragma solidity ^0.8.26;

/// @title SurgeVerifier_Layout
/// @notice Storage layout documentation for SurgeVerifier
/// @dev This file is auto-generated by gen-layouts.sh. DO NOT EDIT MANUALLY.
/// @custom:security-contact security@nethermind.io

// solhint-disable max-line-length
//   _owner                         | address                                            | Slot: 0    | Offset: 0    | Bytes: 20  
//   _pendingOwner                  | address                                            | Slot: 1    | Offset: 0    | Bytes: 20  
//   _verifiers                     | mapping(LibProofBitmap.ProofBitmap => struct SurgeVerifier.InternalVerifier) | Slot: 2    | Offset: 0    | Bytes: 32  
//   _historicalMarkings            | mapping(LibProofBitmap.ProofBitmap => mapping(uint48 => bool)) | Slot: 3    | Offset: 0    | Bytes: 32  
