# See: https://golangci-lint.run/usage/configuration/
#
# Note: for VSCode, you must have the following settings to use this configuration:
#
# "go.lintTool": "golangci-lint",
# "go.lintFlags": [
#   "--fast",
#   "--config=${workspaceFolder}/.golangci.yml"
# ],

run:
  timeout: 20m
  tests: true

linters:
  enable:
    - errcheck
    - funlen
    - gocognit
    - gocritic
    - gofmt
    # - revive
    # - gosec
    - gosimple
    - lll
    - unused
    - whitespace
    - wsl

linters-settings:
  funlen:
    lines: 350
    statements: 100
  gocognit:
    min-complexity: 75

issues:
  exclude-dirs:
    - bindings
  exclude-rules:
    # Exclude some linters from running on tests files.
    - path: _test\.go
      linters:
        - funlen
    - path: /
      linters:
        - typecheck
