// SPDX-License-Identifier: MIT
pragma solidity 0.8.30;

/// @dev Generated by utils/slotchain/generateGoldenVectors.ts. Do not edit.
/// @custom:security-contact security@taiko.xyz
library SlotChainGoldenVectors {
    uint256 internal constant GOLDEN_VECTOR_COUNT = 323;
    uint256 internal constant GOLDEN_HEX_VECTOR_COUNT = 250;
    uint256 internal constant GOLDEN_UINT_VECTOR_COUNT = 73;
    bytes32 internal constant GOLDEN_VECTOR_NAME_SCHEMA_SHA256 =
        hex"c511676c95f722207258c19d0410c971db099c6d23eecf52b30cb1027373f664";

    bytes32 internal constant ADMISSION_PROOF_DIGEST =
        hex"65a5501dc5440301031bc0d21ac6506ce1f98b226139c93ab54251883d5bd12d";
    bytes32 internal constant ADMISSION_REUSE_ROOT =
        hex"a1e22890dd835872055e53dcad82d9e12759a2920853fe6e9f735d7f2c87ceca";
    bytes32 internal constant ADMISSION_ROOT =
        hex"3bf2dcaf78292c832108e29205bf99cc2d22137a0545e4528d8da7309d4b482b";
    bytes32 internal constant ASYMMETRIC_DATA_LEAF =
        hex"204849a6179174bd92e677b252370e3e2904cf4eb2a94fe1ba154e1310b9cd64";
    bytes32 internal constant ASYMMETRIC_MANIFEST_LEAF =
        hex"92ed7b0f26f1048042ad681be312e3d79d6942ea6da03445c1cc8fd6b1eb1d6b";
    bytes32 internal constant BASE_CANONICAL =
        hex"7209a0d225dd6f54483f24072ebf0fe258d73815ee54735f0ee6f505856c2857";
    bytes32 internal constant BLOCK_STRUCT_HASH =
        hex"55021a9fe6408f6bbe52bad826bf24e65cbee639fac8f5266817f3b5c3cf0d78";
    bytes32 internal constant BODY_ROOT =
        hex"0f4e161a46c8b18c2a86f23a0a4e7169a838a12af8b389f65e97b547a99707e9";
    bytes32 internal constant BUILDER_ACTIVE_EQUIVOCATION_WITNESS_HASH =
        hex"188ff80cdad2d9fa2ddd8ad27b943a478dca3558d5467405494abd29e9f4a792";
    uint256 internal constant BUILDER_ACTIVE_EQUIVOCATION_WITNESS_LENGTH = 2366;
    bytes32 internal constant BUILDER_ACTIVE_TRANCHE_RELEASE_WITNESS_HASH =
        hex"2246b6c4067d8dbfffd57072507c4fa03fa9f59b18747907fdde87cf4fbc2c8d";
    uint256 internal constant BUILDER_ACTIVE_TRANCHE_RELEASE_WITNESS_LENGTH = 480;
    bytes32 internal constant BUILDER_ADMISSION_STATE_RETURN_HASH =
        hex"4adb66ffb320e14ef37f1630bacdd71f03bcdfbb006d0c1a15a0312c3b80a91d";
    bytes4 internal constant BUILDER_ADMISSION_STATE_SELECTOR = hex"4a9dfa3f";
    bytes32 internal constant BUILDER_CELL_63_ADMISSION_ROOT =
        hex"a7331d780dab70d17c02c0cedf929a63f970b0baef2c456688c21537efcd1845";
    bytes4 internal constant BUILDER_CLAIM_BUILDER_LEASE_CREDIT_SELECTOR = hex"8f73793c";
    bytes32 internal constant BUILDER_CLAIM_CREDIT_CALLDATA_HASH =
        hex"870c91e9f2ed3494f25ca60447440e8af94c7fe849aeaca24c7020cbe2dad7c2";
    uint256 internal constant BUILDER_CLAIM_CREDIT_CALLDATA_LENGTH = 36;
    bytes32 internal constant BUILDER_CLAIM_CREDIT_RETURN_HASH =
        hex"84a21bcf213c894bd35733058dfa3a592bbe8a1ae5f74e36ff3be371c0c3be9b";
    uint256 internal constant BUILDER_CLAIM_CREDIT_RETURN_LENGTH = 96;
    bytes32 internal constant BUILDER_EQUIVOCATION_CALLDATA_HASH =
        hex"bd470ac24fe185aca71cff7e8c27944e78baae430628101075916cfb15ffbf0b";
    uint256 internal constant BUILDER_EQUIVOCATION_CALLDATA_LENGTH = 2436;
    bytes32 internal constant BUILDER_EQUIVOCATION_RETURN_HASH =
        hex"fcaa313c4629faefccf8365921d57c60c39226a8ead0d46375066aaa4d61f8cb";
    uint256 internal constant BUILDER_EQUIVOCATION_RETURN_LENGTH = 288;
    bytes32 internal constant BUILDER_EXPIRE_SCHEDULE_CALLDATA_HASH =
        hex"4f1b5f49458cc8f4f22f9745a61accc177cd37d4412bfadd74c9c5006b9083f5";
    uint256 internal constant BUILDER_EXPIRE_SCHEDULE_CALLDATA_LENGTH = 36;
    bytes32 internal constant BUILDER_EXPIRE_SCHEDULE_RETURN_HASH =
        hex"347b76314feb452be5b5f8dfa655b368cf0ae1656b7e14e0488b4bc170d0ac6f";
    uint256 internal constant BUILDER_EXPIRE_SCHEDULE_RETURN_LENGTH = 96;
    bytes4 internal constant BUILDER_EXPIRE_SCHEDULE_WINDOWS_SELECTOR = hex"b1357479";
    bytes32 internal constant BUILDER_GENERATION_RELEASE_WITNESS_HASH =
        hex"65a5501dc5440301031bc0d21ac6506ce1f98b226139c93ab54251883d5bd12d";
    uint256 internal constant BUILDER_GENERATION_RELEASE_WITNESS_LENGTH = 352;
    bytes32 internal constant BUILDER_LIABILITY_EQUIVOCATION_WITNESS_HASH =
        hex"0519c74fd1e6a928712e539113d78caf24abf2cd39bb6fc8fe3e807861403897";
    uint256 internal constant BUILDER_LIABILITY_EQUIVOCATION_WITNESS_LENGTH = 2366;
    bytes32 internal constant BUILDER_LIABILITY_TRANCHE_RELEASE_WITNESS_HASH =
        hex"8d56574545d36cb4cbb7f1452055275a3dbd8e5b2aa9062e717095f387a0a2d8";
    uint256 internal constant BUILDER_LIABILITY_TRANCHE_RELEASE_WITNESS_LENGTH = 288;
    bytes32 internal constant BUILDER_MAINTENANCE_CALLDATA_HASH =
        hex"43c78baee19458e9328ff2b4da6b599d2837762bc2c59fd3bd2c99c9a4ef90ae";
    uint256 internal constant BUILDER_MAINTENANCE_CALLDATA_LENGTH = 1316;
    bytes32 internal constant BUILDER_MAINTENANCE_RETURN_HASH =
        hex"71d89327348795bdfb10797b1a4d8fbed80736e9e283d99f004dd4a3eeb3ca55";
    uint256 internal constant BUILDER_MAINTENANCE_RETURN_LENGTH = 160;
    bytes32 internal constant BUILDER_MAINTENANCE_WITNESS_HASH =
        hex"d39a171735fce188e821a1f30d45690e429d1980c8a9ca784d197fc9146fd67b";
    uint256 internal constant BUILDER_MAINTENANCE_WITNESS_LENGTH = 1197;
    bytes32 internal constant BUILDER_MOVE_FINAL_ROOT =
        hex"6ffdad931d0bc04bd668e66d5deb74ce13feb987ad05525f2e1634e1dc4ccc95";
    bytes32 internal constant BUILDER_MOVE_INTERMEDIATE_ROOT =
        hex"e65acea99c98a79044078e8835688758b97b5fb9931f449ab785b3aa3ab3809c";
    bytes32 internal constant BUILDER_MOVE_PRE_ROOT =
        hex"3e961c42d94ba762f1d8e855bc9ac168bcdcd35177c381403574ae2c5fa03a0e";
    bytes32 internal constant BUILDER_MOVEMENT_WITNESS_HASH =
        hex"03028017c34313fc451f9327085f6cbe2f2d24c05303a7d29c69c035b9e689d0";
    uint256 internal constant BUILDER_MOVEMENT_WITNESS_LENGTH = 1193;
    bytes4 internal constant BUILDER_NORMALIZE_BUILDER_TRANCHES_SELECTOR = hex"5e7c8afe";
    bytes32 internal constant BUILDER_NORMALIZE_CALLDATA_HASH =
        hex"a5fe18f847780330e44bfd30b196a3aefb5bdd60a0c5bcfc2160d1dcf4738f65";
    uint256 internal constant BUILDER_NORMALIZE_CALLDATA_LENGTH = 644;
    bytes32 internal constant BUILDER_NORMALIZE_NOOP_WITNESS_HASH =
        hex"bc36789e7a1e281436464229828f817d6612f7b477d66591ff96a9e064bcc98a";
    uint256 internal constant BUILDER_NORMALIZE_NOOP_WITNESS_LENGTH = 1;
    bytes32 internal constant BUILDER_NORMALIZE_RETURN_HASH =
        hex"a1074a8b86686267c3a23a084c9a9ae67808925eb857e4c87f66904cb354e098";
    uint256 internal constant BUILDER_NORMALIZE_RETURN_LENGTH = 160;
    bytes32 internal constant BUILDER_NORMALIZE_WITNESS_HASH =
        hex"41aa2500f6787f0ff38398f6a481ab02641b948e56609939ae1ac4311a05eaa7";
    uint256 internal constant BUILDER_NORMALIZE_WITNESS_LENGTH = 489;
    bytes4 internal constant BUILDER_PROCESS_BUILDER_MAINTENANCE_SELECTOR = hex"0e1ffc68";
    bytes32 internal constant BUILDER_PROOF_ADMISSION_CALLDATA_HASH =
        hex"419032e2b6eb7dc900b2ad948d4fa3c0ad0eae90a8f4bf3a87d3883ee3fd3ea8";
    bytes32 internal constant BUILDER_PROOF_ADMISSION_REQUEST_HASH =
        hex"99c130943aa4780be4a2888146d65d62bad146f46ab501c39b38f19a267e667d";
    uint256 internal constant BUILDER_PROOF_ADMISSION_REQUEST_LENGTH = 531;
    bytes32 internal constant BUILDER_PROOF_ADMISSION_RETURN_HASH =
        hex"cf28cb14abba8c850ef3ab57e04daa0d509f7151fda16cf43b8565b0e95eaa07";
    bytes32 internal constant BUILDER_PROOF_EVIDENCE_ACTIVE_TOMBSTONED_REQUEST_HASH =
        hex"ee5512b2463e0210542cf8eb828155af1350a55233b2b62fdc70ddd349e71779";
    bytes32 internal constant BUILDER_PROOF_EVIDENCE_ACTIVE_TOMBSTONED_RETURN_HASH =
        hex"cb5abdc479e27be56ee55b71b2117f66464be6879bb95abee3c81c3649b49f91";
    bytes32 internal constant BUILDER_PROOF_EVIDENCE_CALLDATA_HASH =
        hex"19d0989aa0370f230bd444bf6e0a939b13e82a4ae20d4f7808effd4806c35bde";
    bytes32 internal constant BUILDER_PROOF_EVIDENCE_LIABILITY_FIRST_REQUEST_HASH =
        hex"efa1540bab4bd531d15ffe972f5f17e2180044d826753c47b9c7bf1e6ff293cd";
    bytes32 internal constant BUILDER_PROOF_EVIDENCE_LIABILITY_FIRST_RETURN_HASH =
        hex"22b13b07658cc56c9726d28fa533ceeaa83aeabd906ece1cf2771592e08b968b";
    bytes32 internal constant BUILDER_PROOF_EVIDENCE_LIABILITY_TOMBSTONED_REQUEST_HASH =
        hex"b5d06e6424135404f0bdd0947d54b1e8aa44020d391ef32b3f7e2809be1344cb";
    bytes32 internal constant BUILDER_PROOF_EVIDENCE_LIABILITY_TOMBSTONED_RETURN_HASH =
        hex"e365e30b1b1119801867813f82b78b16243a0a5734fbaa6b61c127acb3558748";
    bytes32 internal constant BUILDER_PROOF_EVIDENCE_REQUEST_HASH =
        hex"2c3d0d91e2ec5129f13dd6bc89995fa9443120b49b94bac799d0e7e18fd33f00";
    uint256 internal constant BUILDER_PROOF_EVIDENCE_REQUEST_LENGTH = 2727;
    bytes32 internal constant BUILDER_PROOF_EVIDENCE_RETURN_HASH =
        hex"38fe48ff2340f26b97dcf96c9b2f7ddb79504263f6ca9d5c031d981db5b66a98";
    bytes32 internal constant BUILDER_PROOF_IDENTITY_CALLDATA_HASH =
        hex"0efda928731baac8c13e31a788b6856c167cb3d5cb43cc8460414ddba5c757ff";
    uint256 internal constant BUILDER_PROOF_IDENTITY_CALLDATA_LENGTH = 2468;
    bytes32 internal constant BUILDER_PROOF_IDENTITY_RETURN_HASH =
        hex"743733693b186704f091e1e5736ae0f380f5b3d596e5f785517200cdfd4e46d8";
    uint256 internal constant BUILDER_PROOF_IDENTITY_RETURN_LENGTH = 352;
    bytes4 internal constant BUILDER_PROOF_IDENTITY_SELECTOR = hex"7c09d62d";
    bytes32 internal constant BUILDER_PROOF_REGISTRY_CALLDATA_HASH =
        hex"3bc203afce7c1aeb21360ea97544bc6991a216025b5ce2c37e065a4bc1588246";
    bytes32 internal constant BUILDER_PROOF_REGISTRY_REQUEST_HASH =
        hex"63fa85a7efd66ff4db6c06fdd6dbfa44541d8274c1ca8739daa9796f382ff10a";
    uint256 internal constant BUILDER_PROOF_REGISTRY_REQUEST_LENGTH = 432;
    bytes32 internal constant BUILDER_PROOF_REGISTRY_RETURN_HASH =
        hex"b6bfdd1639eae8c9bc92931a3f9f4003e94facbb024e0c057143ef96b0812d7b";
    bytes4 internal constant BUILDER_PROOF_REQUEST_SELECTOR = hex"a9ca9190";
    bytes32 internal constant BUILDER_PROOF_TRANCHE_CALLDATA_HASH =
        hex"5b5ed9cdd24cab6214555f3c72269b69c17bb2d2f344dbf4c213b9b840ca023c";
    bytes32 internal constant BUILDER_PROOF_TRANCHE_REQUEST_HASH =
        hex"f565dd15d53c115c993356953af777950dc0408106a85a53501da7b54fdb762d";
    uint256 internal constant BUILDER_PROOF_TRANCHE_REQUEST_LENGTH = 412;
    bytes32 internal constant BUILDER_PROOF_TRANCHE_RETURN_HASH =
        hex"bdb8ef492f2577f446427641525c5ce4cfbc07f462e4858d834b9ef9343e44a5";
    bytes32 internal constant BUILDER_PROOF_VERIFIER_CONFIG_HASH =
        hex"e3e45065c704e9bdad17d5b1a8de56115576b30d7e4e09d50a3a07aa66aac80b";
    bytes32 internal constant BUILDER_PROOF_VERIFIER_CONFIG_RETURN_HASH =
        hex"424eb74a70eb5383c3ca04922b259ce7314377be45a1b10e5dd0c7ab79df6419";
    bytes4 internal constant BUILDER_PROOF_VERIFIER_CONFIG_SELECTOR = hex"0d1c9932";
    bytes4 internal constant BUILDER_REGISTER_BUILDER_SELECTOR = hex"5fc42c69";
    bytes32 internal constant BUILDER_REGISTER_CALLDATA_HASH =
        hex"9f18fd55e769f2cb66a0886f78c2c27e975a5cc1bd6a91cc505587350ecf12d3";
    uint256 internal constant BUILDER_REGISTER_CALLDATA_LENGTH = 708;
    bytes32 internal constant BUILDER_REGISTER_RETURN_HASH =
        hex"4297459afb1ea5b55dfde89615c2fc6fcf9a3c5169992544cf455ac40b34d3fd";
    uint256 internal constant BUILDER_REGISTER_RETURN_LENGTH = 192;
    bytes32 internal constant BUILDER_REGISTRY_CONFIGURATION_HASH =
        hex"5c2fe6d16935d1557c545b24c0b5982391f7a8ac702d7db3a6c55e467427ed79";
    bytes32 internal constant BUILDER_REGISTRY_EXHAUSTED_HEADER_WORD =
        hex"4252483101400100ffffffffffffffffffffffffffffffff0000000000000000";
    bytes32 internal constant BUILDER_REGISTRY_HEADER_SLOT =
        hex"e7ce7a505bf18b9ed57a0785851385323c9487991c55b422861381f92e5c245a";
    bytes32 internal constant BUILDER_REGISTRY_HEADER_TRIE_KEY =
        hex"3dc336ad17079f9525d2b0708a8773321ab29957d522a6f2d10fc522b7362aec";
    bytes32 internal constant BUILDER_REGISTRY_HEADER_WORD =
        hex"42524831013f0000010203040506070811121314151617182122232425262728";
    bytes32 internal constant BUILDER_REGISTRY_ROOT_SLOT =
        hex"4dc6f1bf199f7518c646d40ed35ca04703f646273e6de1d7eace0746cc7100a6";
    bytes32 internal constant BUILDER_REGISTRY_ROOT_TRIE_KEY =
        hex"04bafd6333ae949248e59a002ce1fbccb8a4bc8da3a0c3228ae523d727170880";
    bytes4 internal constant BUILDER_RELEASE_BUILDER_GENERATION_SELECTOR = hex"e7bae370";
    bytes4 internal constant BUILDER_RELEASE_BUILDER_TRANCHE_SELECTOR = hex"f8668bb9";
    bytes32 internal constant BUILDER_RELEASE_GENERATION_CALLDATA_HASH =
        hex"3a737cfe76c2cd421f226d122366b8eb4b2c0d15ff8ce9ee9662fb1ebdbd0ef5";
    uint256 internal constant BUILDER_RELEASE_GENERATION_CALLDATA_LENGTH = 484;
    bytes32 internal constant BUILDER_RELEASE_GENERATION_RETURN_HASH =
        hex"e10ddf1201ccd056229850f387844bb41a5dc22095e1d6eaff44aaee1dda7705";
    uint256 internal constant BUILDER_RELEASE_GENERATION_RETURN_LENGTH = 192;
    bytes32 internal constant BUILDER_RELEASE_TRANCHE_CALLDATA_HASH =
        hex"3abab4635081cb16695ba53983b7f77f512196f554b9d02a4f523dc265e87fea";
    uint256 internal constant BUILDER_RELEASE_TRANCHE_CALLDATA_LENGTH = 644;
    bytes32 internal constant BUILDER_RELEASE_TRANCHE_RETURN_HASH =
        hex"0775b71ba1f5c778f429c183127db5b39699a4c28a34acd8c9c7e43e59472d3f";
    uint256 internal constant BUILDER_RELEASE_TRANCHE_RETURN_LENGTH = 224;
    bytes4 internal constant BUILDER_REQUEST_BUILDER_EXIT_SELECTOR = hex"c8f20b55";
    bytes32 internal constant BUILDER_REQUEST_EXIT_CALLDATA_HASH =
        hex"83df22506dc47e476d2f4ffac8545afbda7c63d90e099ff0f531d81928a48297";
    uint256 internal constant BUILDER_REQUEST_EXIT_CALLDATA_LENGTH = 36;
    bytes32 internal constant BUILDER_REQUEST_EXIT_RETURN_HASH =
        hex"2b6bf8ef73a6acb0795c0cd086f3c906b83d2883f555b6b163a468bf41645fb9";
    uint256 internal constant BUILDER_REQUEST_EXIT_RETURN_LENGTH = 128;
    bytes4 internal constant BUILDER_RESERVE_BUILDER_WINDOW_SELECTOR = hex"46a53315";
    bytes32 internal constant BUILDER_RESERVE_CALLDATA_HASH =
        hex"7042284258b75a7e1154eb3d9ed48780c1099ef78ac5cb4d1f71222064dfd3f7";
    uint256 internal constant BUILDER_RESERVE_CALLDATA_LENGTH = 932;
    bytes32 internal constant BUILDER_RESERVE_RETURN_HASH =
        hex"84d4b9be382a7c941e0af0304e4feec46929c40ca71770121c21b08afef7aced";
    uint256 internal constant BUILDER_RESERVE_RETURN_LENGTH = 160;
    bytes32 internal constant BUILDER_RESERVE_WITNESS_HASH =
        hex"e41b49dd7050df0b699dfe13a197c0ca366bfed9f06d8f823771f678a565d409";
    uint256 internal constant BUILDER_RESERVE_WITNESS_LENGTH = 777;
    bytes32 internal constant BUILDER_SCHEDULE_REGISTRY_STATE_RETURN_HASH =
        hex"4abc972ad2bcb73d21e82e60a4fba80df1c6646fa376fe873da7eecae3baa492";
    bytes4 internal constant BUILDER_SCHEDULE_REGISTRY_STATE_SELECTOR = hex"ad95cea1";
    bytes32 internal constant BUILDER_SCHEDULE_WINDOW_RELEASE_RETURN_HASH =
        hex"f0160669e33a104e916a3d5bdf5c3051fbe0f06ab42a445ccd7708631e64b77e";
    bytes4 internal constant BUILDER_SCHEDULE_WINDOW_RELEASE_SELECTOR = hex"f4cd9a5e";
    bytes32 internal constant BUILDER_SETTLEMENT_SCHEDULE_RELEASE_RETURN_HASH =
        hex"dad610bad2145e2431a6a6298f62dc7e08fc01f5a80d6f933a91b557a4ee9a84";
    bytes4 internal constant BUILDER_SETTLEMENT_SCHEDULE_RELEASE_SELECTOR = hex"a4574c77";
    bytes4 internal constant BUILDER_SUBMIT_BUILDER_EQUIVOCATION_SELECTOR = hex"979c1f72";
    bytes32 internal constant BUILDER_VACANCY_REGISTRATION_WITNESS_HASH =
        hex"5338baeca36696fec8f42f2f4f9d183c182f5ebc479478e0e4c9e59c9355771b";
    uint256 internal constant BUILDER_VACANCY_REGISTRATION_WITNESS_LENGTH = 544;
    bytes32 internal constant CANDIDATE_COMMITMENT =
        hex"1478b5999deac0929581369516027f5bf1c5b353a27356ea1530cd6646dd0308";
    bytes32 internal constant CANDIDATE_COMMITMENT_2 =
        hex"c6bf847e5660ae4b6d914d00d28506d5dec24955f7130722c8f0e616cd69974d";
    bytes32 internal constant CANDIDATE_COMMITTED_V2_DATA_HASH =
        hex"f48d42355288f3da84b490bc7c2a08935b3a62130fd5ab316aac8d87eaf88c3e";
    uint256 internal constant CANDIDATE_COMMITTED_V2_DATA_LENGTH = 192;
    bytes32 internal constant CANDIDATE_COMMITTED_V2_TOPIC =
        hex"51629f6515f461b4c6f912a8eecad46d8ff89ab5e8235d95c30004be2c9ac738";
    bytes32 internal constant CANDIDATE_COMMITTED_V2_TOPIC1_CANDIDATE_ID =
        hex"39c621a869a95ddaf350d45f0c67094a57ac24d7b36a9bd1f57a75d5310dce2b";
    bytes32 internal constant CANDIDATE_COMMITTED_V2_TOPIC2_BENEFICIARY =
        hex"000000000000000000000000000000000000000000000000000000000000cafe";
    uint256 internal constant CANDIDATE_COMMITTED_V2_TOPIC_COUNT = 3;
    bytes32 internal constant CANDIDATE_COMMITTED_V2_TOPICS_HASH =
        hex"2bd53ab73ae6841a50e7e17af3fb0204ffe1bab823e523017bbb0cf0b32072e4";
    bytes32 internal constant CANONICAL_CORE =
        hex"0362d14c4c2fc6293710a0ca8cf2e19f83a5555ecab59bd19b4f58a75d587091";
    bytes32 internal constant CHUNK_ROOT_0 =
        hex"e652cb05b1f44f3c09c650870b7b9ade4132548bd0c769bdda35b5bfcac5139e";
    bytes32 internal constant CLAIM_REWARD_V1_CALLDATA_HASH =
        hex"dc435de2896a3f9fba5006cb40107aee657dfdd19153f52a09e6fc537aa9922d";
    uint256 internal constant CLAIM_REWARD_V1_CALLDATA_LENGTH = 36;
    uint256 internal constant CLAIM_REWARD_V1_PAID_WEI = 1_000_000;
    bytes32 internal constant CLAIM_REWARD_V1_RETURN_HASH =
        hex"c1af4b94166cd32fc49b7b926cbb91ee421de2d04450e8ae57857b9b56ac7e53";
    uint256 internal constant CLAIM_REWARD_V1_RETURN_LENGTH = 32;
    bytes4 internal constant CLAIM_REWARD_V1_SELECTOR = hex"aa5498cb";
    uint256 internal constant COMPONENT_CONFIG_GETTER_GAS_LIMIT = 50_000;
    bytes4 internal constant COMPONENT_CONFIG_GETTER_SELECTOR = hex"f6c0f7d2";
    bytes32 internal constant DATA_MMR_FRONTIER_AFTER_3_DIGEST =
        hex"7e141a72088ecc5ed590e1e619b607fb5d97aafb003c4a56230cff2832c2af01";
    bytes32 internal constant DATA_MMR_FRONTIER_ROOT_3 =
        hex"dea2c7de9f14ce6f9c59fda963520ced2cb6e6ebef7c6abe6cb773afab888e89";
    bytes32 internal constant DATA_MMR_MOUNTAIN_SIBLINGS_DIGEST =
        hex"3ad2e114ce1d543a3a479e69b945dfeabdfdd0fc6df543b28c069469ea5e26fa";
    bytes32 internal constant DATA_MMR_OTHER_PEAKS_DIGEST =
        hex"d5b32274fe3e21ffa9dbaf5853b469ecaaf4ac295e788fc95c16b4220a00b196";
    uint256 internal constant DATA_MMR_PROOF_COUNT = 15;
    uint256 internal constant DATA_MMR_PROOF_INDEX = 10;
    bytes32 internal constant DATA_MMR_PROOF_LEAF =
        hex"39d13a13b5803fd94af45496a7b19e2e666957cd75780ed2508c702a703ca85b";
    bytes32 internal constant DATA_MMR_PROOF_ROOT =
        hex"7c7185dfbebadab3501e051b2960e8fb4b22dd11821fc4e474ef14b2edb27b22";
    bytes32 internal constant DATA_NODE_HEIGHT_7 =
        hex"e60d61327adb017addbf3012131b62c0a5897d30e302fcfac9ffad46d0fe848a";
    bytes32 internal constant DATA_RECORD_APPENDED_TOPIC =
        hex"30ee2de166c53a480d028e5b94d4f8759dbd84b5f7b6af1f23e0c5889ea17f8c";
    uint256 internal constant DATA_SESSION_ACCOUNTING_RETURN_LENGTH = 512;
    bytes32 internal constant DATA_SESSION_CONFIG_HASH =
        hex"c8db58336498ffd3cfaa755c1769d44c6a61f9675d5a0b76d18b30603fc78c7b";
    bytes32 internal constant DATA_SESSIONS_MAINTAINED_TOPIC =
        hex"920669b9670911aa86cd718dceebaa1372d224ca0fdac50a63dc1d45a53e1e89";
    bytes32 internal constant DOMAIN_SEPARATOR =
        hex"e68571dca46842abc561c1ea35b556152b15d93a1d29f5c441ae2fdcdd01725c";
    bytes32 internal constant EIP712_DIGEST =
        hex"71dbc886b2be3e2a2b692976ca6b0e42957915d83df76859637a08c92f7a24d1";
    bytes32 internal constant EMPTY_ADMISSION_ROOT =
        hex"71a511ce5247c6c3b0411e182c8e4b4dcbd0adc97163c585cac94ca3b031ac54";
    bytes32 internal constant EMPTY_BODY_ROOT =
        hex"f0e00da8dbc00feb028a8bc92342c0771372b947acf5989b2d4a5f23bb2f459a";
    bytes32 internal constant EMPTY_DATA_BAG =
        hex"b3caa2379816b63eebbf789e33e7d84ef29d6d350179803dd000102e8182f66a";
    bytes32 internal constant EMPTY_DATA_SESSION_ACCOUNTING_RETURN_HASH =
        hex"9c469322ff55a06e16032b8017d6190d9e339927e68bb7855d72afc32fdaeab6";
    bytes32 internal constant EMPTY_ENTRY_ROOT =
        hex"986d3e795bd9ddfabe213b93cea0211eea5a663e895bfc112d90c5bf2fff1564";
    bytes32 internal constant EMPTY_FORCED_ROOT =
        hex"4001bca0d3c5171a99a50118f1219024e1bef9302262ea3b075ecbed36be7592";
    bytes32 internal constant EMPTY_MANIFEST_ROOT =
        hex"0bb15f38645cecc1748b17fe3bd966ba8016c169ebd1266fd38150766177b5f6";
    bytes32 internal constant EMPTY_REGISTRY_ROOT =
        hex"2f40c290594200091bcd31881e40bf56ba1960016a24c9931cf3b1a9a8705ae8";
    bytes32 internal constant EMPTY_SESSION_LIST =
        hex"8827f09b5799bab18f29ea5b9cb9cbb5a88ddb96bc4b3ffc4d69cbcbdfe50279";
    bytes32 internal constant EMPTY_TRANCHE_ROOT =
        hex"dee49bfb4494eee086cf6485f471866cd49591358b3490d4a156813702501768";
    bytes32 internal constant ENQUEUE_FORCED_TRANSACTION_CALLDATA_HASH =
        hex"3e802e6f72e50c267cc18d256c2863d04446eb8f2d47bc474bbcb9c68876d19a";
    uint256 internal constant ENQUEUE_FORCED_TRANSACTION_CALLDATA_LENGTH = 196;
    bytes4 internal constant ENQUEUE_FORCED_TRANSACTION_SELECTOR = hex"9f06b1b4";
    bytes32 internal constant ENTRY_PROOF_DIGEST =
        hex"89655918472451054bf7362e8e7b19bbded634877c532efdfb545e0ca36667f3";
    bytes32 internal constant ENTRY_ROOT =
        hex"acee83a690b868a4a7960c55a9f7228f91cad26b704e24106d4db87e9c7a8f34";
    bytes32 internal constant EXECUTION_OUTPUTS =
        hex"01ab23ac7b0a92af32ace3220c3b181ef983f4be274c997ef2d4b50d9c7669cd";
    bytes32 internal constant EXPECTED_OLD_FORK_REGISTRATION_HASH =
        hex"eed5e788c296e7b8449f4aacb62cd9e5b15ec488dc667f4cf3e3aa48a244c6c5";
    bytes32 internal constant EXPECTED_PREDECESSOR_FORK_REGISTRATION_HASH =
        hex"233d72ef0935f897e49377ce160962e2ea7ea14c37c309bb094b78e0b50bb118";
    bytes32 internal constant FORCE_FRONTIER_AFTER_1_DIGEST =
        hex"1ba50296675195de90944defd33d2e346c1a996aa6edbb5bfb1b187cc64b3c1d";
    bytes32 internal constant FORCE_FRONTIER_ROOT_1 =
        hex"5cb37cac8283fe7742e0f8e40bacececf85c1f8c15a05c8a9c9dc2018ac532e8";
    bytes32 internal constant FORCE_RANGE_DIGEST =
        hex"75c75611d9eaa6c05e56a1fb646cea4c9d796adfd205df5c5ff1b0b52cc93dd2";
    bytes32 internal constant FORCED_DESCRIPTORS =
        hex"ccc81a65638181195f6ebd5b5902bc3a62716d7c3e70b32cbabdd250b9ebf42f";
    bytes32 internal constant FORCED_LEAF =
        hex"c75c50d8b8573f217a20c9018a3d23d7fa5cda240f2a2e9eb4260c4af4c367e4";
    bytes4 internal constant FORCED_QUEUE_ADVANCE_SELECTOR = hex"d59ff200";
    bytes32 internal constant FORCED_QUEUE_APPENDED_TOPIC =
        hex"79250628d474df83f40598f02c49d25e713fb04a8ef4bd4457fa70055a86f489";
    bytes32 internal constant FORCED_QUEUE_CLAIM_WITHDRAWN_TOPIC =
        hex"93cc2e9cd74702c3df0d771c2b1901ca496935e81636c3e6f0e5d7e0d7f5dd74";
    bytes32 internal constant FORCED_QUEUE_CONFIG_HASH =
        hex"13b9e677d8e94c70282ac3bd4543a22c77fbffb4e7485178da1f622d0ab08492";
    bytes32 internal constant FORCED_QUEUE_CONFIG_RETURN_HASH =
        hex"f79b30bbc63834b3edaea14ca8dd0ffa9af074291da2f61a58c2ffdcf59b4fef";
    uint256 internal constant FORCED_QUEUE_CONFIG_RETURN_LENGTH = 576;
    bytes4 internal constant FORCED_QUEUE_CONFIG_SELECTOR = hex"8136fe31";
    bytes32 internal constant FORCED_QUEUE_CURSOR_ADVANCED_TOPIC =
        hex"972ed56e80520f8e90eb897f4f0e5b59f1167d96d3b28e0432f80c96c53aff17";
    bytes4 internal constant FORCED_QUEUE_DESCRIPTOR_SELECTOR = hex"bd9534db";
    bytes4 internal constant FORCED_QUEUE_DUE_AT_SELECTOR = hex"530fd138";
    bytes32 internal constant FORCED_QUEUE_EMPTY_STATE_RETURN_HASH =
        hex"5d2dedefae83c15a5ed51edff0a17e7287115c363d527cfe5c649b39daea32e6";
    bytes4 internal constant FORCED_QUEUE_FRONTIER_SELECTOR = hex"7c339ff7";
    uint256 internal constant FORCED_QUEUE_STATE_RETURN_LENGTH = 320;
    bytes4 internal constant FORCED_QUEUE_STATE_SELECTOR = hex"03e0d70b";
    bytes4 internal constant FORCED_QUEUE_WITHDRAW_SELECTOR = hex"c28aa0e8";
    bytes32 internal constant FORCED_ROOT =
        hex"a54e9f797ffe7f04dd5ca7df4c858edf02ce45a81808522633fc9cee8fe72e57";
    bytes4 internal constant FORK_VERIFIER_INSTALL_MAGIC = hex"46564931";
    bytes4 internal constant FORK_VERIFIER_REGISTRATION_MAGIC = hex"46565231";
    bytes32 internal constant FORK_VERIFIER_REGISTRATION_RETURN_HASH =
        hex"252a8f9b5199a2b88f07e01d89d4fabb49903713d19500ca1cf34ad3fbf9c00f";
    bytes4 internal constant FORK_VERIFIER_REGISTRATION_SELECTOR = hex"c614591c";
    bytes32 internal constant FUND_REWARD_CLASS_V1_CALLDATA_HASH =
        hex"1086e7c6ffda5d1b4d31999795549a413160e18f638c43801cf6bd8293b430f1";
    uint256 internal constant FUND_REWARD_CLASS_V1_CALLDATA_LENGTH = 36;
    uint256 internal constant FUND_REWARD_CLASS_V1_RETURN_LENGTH = 0;
    bytes4 internal constant FUND_REWARD_CLASS_V1_SELECTOR = hex"15e08308";
    bytes32 internal constant FUNDED_DATA_SESSION_ACCOUNTING_RETURN_HASH =
        hex"a2aa2351d0781561b9778f002a067b80863af007f04f583019896e815b6972a6";
    bytes32 internal constant INITIAL_FORK_REGISTRATION_RETURN_HASH =
        hex"d2044ac981fb5358a1354c6ba4ad2bee5f994361fe188f99099e89ba6b62c6dc";
    bytes32 internal constant INITIAL_FORK_ROUTE_STATE_RETURN_HASH =
        hex"ce1242ef9f6de662b939f857e86aa5c8a585bfd78fa3b285d3804b154ac16dbb";
    bytes32 internal constant INITIAL_FORK_VERIFIER_CONFIG_RETURN_HASH =
        hex"ed485e43081733b49a3da6e22a1d1e54126837f94cb816d888bd29f3d3e12b1c";
    bytes32 internal constant INSTALL_FORK_VERIFIER_CALLDATA_HASH =
        hex"67ab3af72e37b0366daf3887450a66395aa7d45fb4114d323d6d80a083ae6dbf";
    bytes4 internal constant INSTALL_FORK_VERIFIER_SELECTOR = hex"9bb6fe73";
    bytes32 internal constant KIND0_FORCED_ADMISSION_HASH =
        hex"3733764f042a48dfc4376c14c2f9c253f3a0ae0fc8e72a1e9e5ffd00aa9a0f3d";
    uint256 internal constant KIND0_FORCED_ADMISSION_LENGTH = 204;
    bytes32 internal constant KIND0_FORCED_ADMISSION_SCHEMA_HASH =
        hex"6c5da3090966e605a84a39083d1e31c8a975527faff01d52a6728eea90c03700";
    bytes32 internal constant MANIFEST_NODE_HEIGHT_5 =
        hex"9f4c64a89c253d4d65f93cba1f55e7a17a3e4027be7351650060632ed1bc70f0";
    bytes32 internal constant MANIFEST_ROOT =
        hex"417be737a57e38eb410f2d6e65c77ee19d5c314cdaf432067861c6a36c6a990f";
    bytes32 internal constant MANIFEST_ROOT_BLOCK_1 =
        hex"c58ab29bdccb3e06cc5431fbbcea1abc6d6f1a38120c5d896e18b7f1ca1cf43e";
    bytes32 internal constant MMR_ROOT_2 =
        hex"d20459aeb2fe916a18dd584d39b2ae25075c6b6c14104d9d64a8b1d7882eb4df";
    bytes32 internal constant MMR_ROOT_3 =
        hex"dea2c7de9f14ce6f9c59fda963520ced2cb6e6ebef7c6abe6cb773afab888e89";
    bytes32 internal constant NORMAL_CONTEXT =
        hex"f13be874ddd561c733c4bebe725fde7f7770661520f73e4bb99c383f40f579e6";
    bytes32 internal constant RECOVERY_ID =
        hex"1d70fb5798b55f7a4b4b2f4b0f8b4472e63b9ff6853011680c516cf614293057";
    bytes32 internal constant REGISTRY_PROOF_DIGEST =
        hex"188d53708f68cd601ace09953d87031b89c92f5b9d7bffd847e324ab7adc8261";
    bytes32 internal constant REGISTRY_ROOT =
        hex"0bf297d7b9b6a5529a319a06cb08484923a89bab15d51f8baeaf5c30bebdf3fd";
    bytes32 internal constant REPLACE_PENDING_FORK_VERIFIER_CALLDATA_HASH =
        hex"7f5672e814198405380028deb977bebdad7c69273d1b9b2c72edf8ca26982aca";
    uint256 internal constant REPLACE_PENDING_FORK_VERIFIER_CALLDATA_LENGTH = 548;
    bytes32 internal constant REPLACE_PENDING_FORK_VERIFIER_RETURN_HASH =
        hex"9b9e757b4ebf73b65db810d4bd2da658f26d189916c4b97595c5470ad7972534";
    uint256 internal constant REPLACE_PENDING_FORK_VERIFIER_RETURN_LENGTH = 160;
    bytes4 internal constant REPLACE_PENDING_FORK_VERIFIER_SELECTOR = hex"b48bbef1";
    bytes32 internal constant REWARD_CLAIMED_V1_DATA_HASH =
        hex"db2be80ad7fe2991fbabee31c9917dca99f927a94e09c6a4e810cec6d4a8cbae";
    uint256 internal constant REWARD_CLAIMED_V1_DATA_LENGTH = 64;
    bytes32 internal constant REWARD_CLAIMED_V1_TOPIC =
        hex"9f41046da255bf29062408ae9f20e06ea2453df29227caf32b709ccfed59d506";
    bytes32 internal constant REWARD_CLAIMED_V1_TOPIC1_CANDIDATE_ID =
        hex"39c621a869a95ddaf350d45f0c67094a57ac24d7b36a9bd1f57a75d5310dce2b";
    bytes32 internal constant REWARD_CLAIMED_V1_TOPIC2_BENEFICIARY =
        hex"000000000000000000000000000000000000000000000000000000000000cafe";
    uint256 internal constant REWARD_CLAIMED_V1_TOPIC_COUNT = 3;
    bytes32 internal constant REWARD_CLAIMED_V1_TOPICS_HASH =
        hex"774116b1e415ba1f16dd1c36bdf890120b091c4bddec662346eeb2a1e1c0f0d9";
    bytes32 internal constant REWARD_CLASS_FUNDED_V1_DATA_HASH =
        hex"e1aede520e7a9dc85a896fcdc9cc395ef1f2fd03d93f7e4f6acbd5fda09bf690";
    uint256 internal constant REWARD_CLASS_FUNDED_V1_DATA_LENGTH = 96;
    bytes32 internal constant REWARD_CLASS_FUNDED_V1_TOPIC =
        hex"d979ecc5f5821fb9e6643744111b04290fc1da57eebaba07def52e526c6eb49e";
    bytes32 internal constant REWARD_CLASS_FUNDED_V1_TOPIC1_REWARD_CLASS =
        hex"0000000000000000000000000000000000000000000000000000000000000001";
    bytes32 internal constant REWARD_CLASS_FUNDED_V1_TOPIC2_FUNDER =
        hex"000000000000000000000000000000000000000000000000000000000000f00d";
    uint256 internal constant REWARD_CLASS_FUNDED_V1_TOPIC_COUNT = 3;
    bytes32 internal constant REWARD_CLASS_FUNDED_V1_TOPICS_HASH =
        hex"dec401d3769ac3d7c894189f394a778a66106bd32460f51135caea4824360efe";
    uint256 internal constant REWARD_CLASS_V1_CALL_GAS = 50_000;
    bytes32 internal constant REWARD_CLASS_V1_CALLDATA_HASH =
        hex"3717990a97396f7a0a947025434cf954d9937932f5e00fdf793c129bfbfb3006";
    uint256 internal constant REWARD_CLASS_V1_CALLDATA_LENGTH = 36;
    uint256 internal constant REWARD_CLASS_V1_CLASS_ID = 1;
    bytes4 internal constant REWARD_CLASS_V1_MAGIC = hex"52435631";
    bytes32 internal constant REWARD_CLASS_V1_RETURN_HASH =
        hex"3d21e30cd424ac4eb52ed85673aac8960a703cce5dd930fceb901b0ce5e93490";
    uint256 internal constant REWARD_CLASS_V1_RETURN_LENGTH = 224;
    bytes4 internal constant REWARD_CLASS_V1_SELECTOR = hex"3d273ee7";
    bytes32 internal constant REWARD_RECEIPT_V1_CALLDATA_HASH =
        hex"2a66098a253be726163d7f52e6d14eb134b5fd3651913b5b5a21526cbcc2fefb";
    uint256 internal constant REWARD_RECEIPT_V1_CALLDATA_LENGTH = 36;
    bytes32 internal constant REWARD_RECEIPT_V1_COLLISION_CANDIDATE_ID =
        hex"a4a4a4a4a4a4a4a4a4a4a4a4a4a4a4a4a4a4a4a4a4a4a4a4a4a4a4a4a4a4a42b";
    bytes32 internal constant REWARD_RECEIPT_V1_COMMITMENT =
        hex"e1e5ebd069f797767f88a333cdfc5e3c718a2cbba3ef6aa1ebb6192f307f2923";
    bytes4 internal constant REWARD_RECEIPT_V1_MAGIC = hex"52525631";
    bytes32 internal constant REWARD_RECEIPT_V1_MISSING_RETURN_HASH =
        hex"910614e273a7326ae3c583449cfdf24c64d9ef3d7d6f448b6d3042d3ba95ae80";
    bytes32 internal constant REWARD_RECEIPT_V1_PRESENT_RETURN_HASH =
        hex"23160ce91822c00eda504d61fb874db8cdfaa2a0597332d37661540eebb6b62e";
    uint256 internal constant REWARD_RECEIPT_V1_RETURN_LENGTH = 384;
    bytes4 internal constant REWARD_RECEIPT_V1_SELECTOR = hex"3ed526c7";
    bytes32 internal constant SCHEDULE_CARRIER_RETURN_HASH =
        hex"3e7028adb7b81c521979a0024999718518559b1ddec5cde8e3a9379d6cef3125";
    bytes32 internal constant SCHEDULE_CARRIER_STATEMENT_HASH =
        hex"e5e7ef6967d544c41242fd48103d1a53c28f1d6da31a1649d34f4bd11025e123";
    bytes4 internal constant SCHEDULE_FORK_CARRIER_MAGIC = hex"53464331";
    bytes32 internal constant SCHEDULE_FORK_CONSTANTS_HASH =
        hex"c17afdd5367849af551b3a2f322a2c351321e916ad913a78b646586fe34f59fc";
    bytes32 internal constant SCHEDULE_FORK_OUTPUT_SCHEMA_HASH =
        hex"623a145841922b79691d33358ec5233f02cf68a4176d9e7c2cfafaeb357fa63a";
    bytes32 internal constant SCHEDULE_FORK_ROUTE_STATE_HASH =
        hex"4ada318df9f5ffeb65fa6a0ce68aa2b019746320323628be080fc142dbe255e9";
    bytes4 internal constant SCHEDULE_FORK_ROUTE_STATE_MAGIC = hex"46525331";
    bytes32 internal constant SCHEDULE_FORK_ROUTE_STATE_RETURN_HASH =
        hex"f4433ec078e97ab1615b273d74599b14f3458581e83e7d4dbb1f77dfc65d891e";
    uint256 internal constant SCHEDULE_FORK_ROUTE_STATE_RETURN_LENGTH = 160;
    bytes4 internal constant SCHEDULE_FORK_ROUTE_STATE_SELECTOR = hex"7e9f3c0d";
    bytes4 internal constant SCHEDULE_FORK_VERIFIER_CONFIG_MAGIC = hex"53465631";
    bytes32 internal constant SCHEDULE_FORK_VERIFIER_CONFIG_RETURN_HASH =
        hex"d71c98eddf7e49dfebf8278d29f45aa24a115e507fb309965fcaf8f523409dba";
    bytes4 internal constant SCHEDULE_FORK_VERIFIER_CONFIG_SELECTOR = hex"44efa773";
    bytes32 internal constant SCHEDULE_FORK_VERIFIER_CONFIGURATION_HASH =
        hex"9256c85ac8b81181ff7538f757939218a42c945cb7228ed5755d10f5e4ef643d";
    bytes32 internal constant SCHEDULE_LIST =
        hex"7ab789362dd8b411e1bc42af1270bcb14d2a7571fc28ab614c6afcc33b7de8e7";
    uint256 internal constant SEAT_AUTHORITY_READ_GAS = 100_000;
    bytes4 internal constant SEAT_MARKET_DUTY_SELECTOR = hex"9a649489";
    bytes4 internal constant SEAT_MARKET_TERM_SELECTOR = hex"76d5ecd4";
    bytes4 internal constant SEAT_TARGET_STATE_SELECTOR = hex"cf52185b";
    bytes4 internal constant SESSION_ACCOUNTING_SELECTOR = hex"e2a62969";
    bytes32 internal constant SESSION_BOND_CLAIMED_TOPIC =
        hex"69fe7d8d95811e3a02a4ad4b0d1a3e1360b683a31f7cb30b4c69546b258232fb";
    bytes4 internal constant SESSION_BY_ID_SELECTOR = hex"eeaad0bb";
    bytes4 internal constant SESSION_CELL_SELECTOR = hex"011efada";
    bytes4 internal constant SESSION_CLAIM_SELECTOR = hex"fdd2b0db";
    bytes32 internal constant SESSION_ID =
        hex"98cbb8b158cb6732a806e2fac0e50c53e88feafd5e3dade0a0ed7edeb7a5a0b1";
    bytes32 internal constant SESSION_LIST =
        hex"9cbf4ca60afc8aee2ccaa68a45bb6568a04812cf282aa703f194e017092fb264";
    bytes32 internal constant SESSION_LIVE_TO_REFUND_TOPIC =
        hex"086de7ad4d27cf66f63e9dc6ecb09c0c3122146dd43e7f480f3a875070eb984e";
    bytes4 internal constant SESSION_MAINTAIN_SELECTOR = hex"1e7a916a";
    bytes4 internal constant SESSION_OPEN_SELECTOR = hex"7bda4d11";
    bytes32 internal constant SESSION_OPENED_TOPIC =
        hex"a81132592bd8a549a0bfc83415ab47fbca586f0b48fff5f6cb5bfae0a9fd1f68";
    bytes4 internal constant SESSION_POST_SELECTOR = hex"a1cc526a";
    bytes32 internal constant SESSION_REFUND_FORFEITED_TOPIC =
        hex"f93f771339298d1fb502bd2c556fc18130b95d44599f35109de39d8d5731f957";
    bytes4 internal constant SESSION_SEAL_SELECTOR = hex"340e11fb";
    bytes32 internal constant SESSION_SEALED_TOPIC =
        hex"f6d45ab0ecc3348b36ac48bc769f7391962fc2fa240c1c6bb43269ed3780078e";
    bytes32 internal constant SESSION_SURPLUS_SWEPT_TOPIC =
        hex"3a5f2fa0ab342d3b79fc2aa40be5e1296009e8fb31f86c3577c51839dd159a86";
    bytes4 internal constant SESSION_SWEEP_SELECTOR = hex"9d083a2b";
    uint256 internal constant SETTLEMENT_FORCED_INGRESS_FLOOR_CALL_GAS = 50_000;
    bytes4 internal constant SETTLEMENT_FORCED_INGRESS_FLOOR_MAGIC = hex"53494631";
    bytes32 internal constant SETTLEMENT_FORCED_INGRESS_FLOOR_NORMAL_RETURN_HASH =
        hex"4bfd11163f0bfe60df7c73b3e4e72749e76d7419593668cac1443ea28b0b09b5";
    bytes32 internal constant SETTLEMENT_FORCED_INGRESS_FLOOR_RECOVERY_RETURN_HASH =
        hex"f4d8a492be93a1541f573cae536d3d4811b6251de4ee66c43887342d6597d05f";
    uint256 internal constant SETTLEMENT_FORCED_INGRESS_FLOOR_RETURN_LENGTH = 64;
    bytes4 internal constant SETTLEMENT_FORCED_INGRESS_FLOOR_SELECTOR = hex"fe2a2914";
    bytes32 internal constant SPLIT_LATEST_FORK_VERIFIER_CALLDATA_HASH =
        hex"793eb33ab7e71b38a63b6b04704dbdc816de18915df79b09af7d75c4e812b41b";
    uint256 internal constant SPLIT_LATEST_FORK_VERIFIER_CALLDATA_LENGTH = 516;
    bytes32 internal constant SPLIT_LATEST_FORK_VERIFIER_RETURN_HASH =
        hex"a3e070e8b9e742f15f072cb46690cf08b62bf018a99b83666455adec80e54833";
    uint256 internal constant SPLIT_LATEST_FORK_VERIFIER_RETURN_LENGTH = 160;
    bytes4 internal constant SPLIT_LATEST_FORK_VERIFIER_SELECTOR = hex"455b4ff5";
    bytes32 internal constant STATEMENT_HASH =
        hex"39c621a869a95ddaf350d45f0c67094a57ac24d7b36a9bd1f57a75d5310dce2b";
    uint256 internal constant STATEMENT_REWARD_EXECUTION_GAS = 12_345_678;
    uint256 internal constant STATEMENT_REWARD_PUBLISHED_BYTES = 9;
    bytes32 internal constant TRANCHE_LEAF =
        hex"80fce6c2421807d961f9207d30b439bd423c05e206a18021b93217513ecc5551";
    bytes32 internal constant TRANCHE_PROOF_DIGEST =
        hex"8d56574545d36cb4cbb7f1452055275a3dbd8e5b2aa9062e717095f387a0a2d8";
    bytes32 internal constant TRANCHE_ROOT =
        hex"12ce6da6104ea0fb21edbc0e932f7500fabf18173911a48bc5e1d4d2af1cc336";
    bytes32 internal constant TYPEHASH =
        hex"ee6a8c8e31e8245cd527869508f6e464d6084893991203876f734d1855aed87c";
    bytes32 internal constant VERIFY_SCHEDULE_CARRIER_CALLDATA_HASH =
        hex"a6f4b2260cd81afd71756624c295b886d29e85c0c9e9b1cdc89f0148bbd0fb79";
    uint256 internal constant VERIFY_SCHEDULE_CARRIER_CALLDATA_LENGTH = 132;
    bytes4 internal constant VERIFY_SCHEDULE_CARRIER_SELECTOR = hex"7e981e0b";
    bytes32 internal constant WINNING_DATA =
        hex"8e96cd4712fddeabda80eaa349916e5b2cbf10ccf0df0edcb7c5a2ffd52652fc";
}
