name: Claude Workflow Access Control

# Restrict Claude workflow to repository collaborators only
on:
  workflow_dispatch:
  issue_comment:
    types: [created]
  pull_request:
    types: [opened, synchronize]

jobs:
  check-collaborator-access:
    runs-on: ubuntu-latest
    outputs:
      is-collaborator: ${{ steps.permission-check.outputs.has-permission }}
    steps:
      - name: Check if user is collaborator
        id: permission-check
        uses: actions-cool/has-permission@v1.0.0
        with:
          required-permission: write
          username: ${{ github.actor }}

  claude-workflow:
    needs: check-collaborator-access
    runs-on: ubuntu-latest
    if: needs.check-collaborator-access.outputs.is-collaborator == 'true'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Claude workflow execution
        run: |
          echo "Claude workflow executing for collaborator: ${{ github.actor }}"
          # Add your Claude-specific workflow steps here

      - name: Comment on PR/Issue (if applicable)
        if: github.event_name == 'issue_comment' || github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const message = 'Claude workflow completed successfully for authorized collaborator.';
            if (context.eventName === 'issue_comment') {
              github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: message
              });
            } else if (context.eventName === 'pull_request') {
              github.rest.issues.createComment({
                issue_number: context.payload.pull_request.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: message
              });
            }

  access-denied:
    needs: check-collaborator-access
    runs-on: ubuntu-latest
    if: needs.check-collaborator-access.outputs.is-collaborator == 'false'
    steps:
      - name: Access denied notification
        run: |
          echo "Access denied for user: ${{ github.actor }}"
          echo "Only repository collaborators can trigger Claude workflows"

      - name: Comment access denied (if applicable)
        if: github.event_name == 'issue_comment' || github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const message = '❌ Access denied. Only repository collaborators can trigger Claude workflows.';
            if (context.eventName === 'issue_comment') {
              github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: message
              });
            } else if (context.eventName === 'pull_request') {
              github.rest.issues.createComment({
                issue_number: context.payload.pull_request.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: message
              });
            }