name: Bridge UI CI/CD

on:
  push:
    paths:
      - "packages/bridge-ui/**"
    branches-ignore:
      - dependabot/**
      - release-please--branches--**

  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths:
      - "packages/bridge-ui/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test:
    if: ${{ github.event.pull_request.draft == false  && !startsWith(github.head_ref, 'release-please') && !startsWith(github.head_ref, 'dependabot') }}
    uses: ./.github/workflows/bridge-ui--ci.yml
