name: Bridge UI v2

on:
  push:
    branches: [main]
    paths:
      - "packages/bridge-ui-v2/**"
  pull_request:
    paths:
      - "packages/bridge-ui-v2/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ github.token }}

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install pnpm dependencies
        uses: ./.github/actions/install-pnpm-dependencies

      # This step is needed because the .env file is not committed to the repository
      # and the Svelte check complains about not finding the exports from $env/static/public,
      # which will be generated based on the .env file when running `svelte-kit sync`
      - name: Copy .env.example to .env
        working-directory: ./packages/bridge-ui-v2
        run: cp .env.example .env

      - name: Svelte check
        working-directory: ./packages/bridge-ui-v2
        run: pnpm svelte:check

      - name: Linting
        working-directory: ./packages/bridge-ui-v2
        run: pnpm lint

      - name: Unit tests
        working-directory: ./packages/bridge-ui-v2
        run: pnpm test:unit

      # TODO: Playwright tests?
