name: Claude Storage Layout Review

on:
  workflow_run:
    workflows: ["Protocol"]
    types: [completed]

jobs:
  claude-layout-review:
    # Only run if the Protocol workflow succeeded and this is a PR
    if: |
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.event == 'pull_request'
    runs-on: [arc-runner-set]
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Get PR details
        id: pr
        uses: actions/github-script@v7
        with:
          script: |
            const { data: prs } = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open',
              head: `${context.repo.owner}:${context.payload.workflow_run.head_branch}`,
            });

            if (prs.length === 0) {
              core.setFailed('No open PR found for this branch');
              return;
            }

            const pr = prs[0];
            core.setOutput('number', pr.number);
            core.setOutput('base_ref', pr.base.ref);
            core.setOutput('head_ref', pr.head.ref);

      - name: Checkout code
        uses: actions/checkout@v5
        with:
          ref: ${{ steps.pr.outputs.head_ref }}
          fetch-depth: 0

      - name: Fetch base branch
        run: git fetch origin ${{ steps.pr.outputs.base_ref }}

      - name: Check for layout changes
        id: layout_check
        run: |
          if git diff --name-only origin/${{ steps.pr.outputs.base_ref }}...HEAD | grep -q '_Layout\.sol$'; then
            echo "has_changes=true" >> $GITHUB_OUTPUT
          else
            echo "has_changes=false" >> $GITHUB_OUTPUT
            echo "No storage layout files changed"
          fi

      - name: Run Claude layout review
        if: steps.layout_check.outputs.has_changes == 'true'
        uses: anthropics/claude-code-action@v1
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          prompt: /review-layout ${{ steps.pr.outputs.base_ref }}
          claude_args: |
            --allowed-tools Read,Grep,Glob,Bash
