name: "overseer CI"

permissions:
  contents: read

on:
  push:
    branches: [main]
    tags:
      - "overseer-rs-v*"
    paths:
      - "packages/overseer-rs/**"
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths:
      - "packages/overseer-rs/**"
      - "!**/*.md"
    branches-ignore:
      - release-please--branches--**

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  RUST_TOOLCHAIN: stable
  REGISTRY_IMAGE: us-docker.pkg.dev/evmchain/images/overseer-rs

jobs:
  lint:
    if: ${{ github.event_name == 'push' || (github.event.pull_request.draft == false && !startsWith(github.head_ref, 'release-please') && !startsWith(github.head_ref, 'dependabot')) }}
    name: Lint
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4

      - name: Setup Rust cache
        uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true
          key: ${{ runner.os }}-overseer-rs-${{ hashFiles('packages/overseer-rs/Cargo.lock') }}

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ env.RUST_TOOLCHAIN }}
          components: clippy, rustfmt

      - name: Run fmt check
        working-directory: packages/overseer-rs
        run: cargo fmt -- --check

      - name: Run clippy
        working-directory: packages/overseer-rs
        run: cargo clippy --all-targets -- -D warnings

  test:
    if: ${{ github.event_name == 'push' || (github.event.pull_request.draft == false && !startsWith(github.head_ref, 'release-please')) }}
    name: Tests
    runs-on: ubuntu-latest
    timeout-minutes: 15
    needs: lint

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.12.1
        with:
          access_token: ${{ github.token }}

      - uses: actions/checkout@v4

      - name: Setup Rust cache
        uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true
          key: ${{ runner.os }}-overseer-rs-${{ hashFiles('packages/overseer-rs/Cargo.lock') }}

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ env.RUST_TOOLCHAIN }}
          components: clippy, rustfmt

      - name: Run tests
        working-directory: packages/overseer-rs
        run: cargo test
