name: "Build and Push Multi-Arch Docker Image (relayer)"

permissions:
  contents: read

on:
  push:
    branches: [main]
    tags:
      - "relayer-v*"
    paths:
      - "packages/relayer/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  REGISTRY_IMAGE: us-docker.pkg.dev/evmchain/images/relayer

jobs:
  push-relayer-docker-image:
    name: Build and push docker image
    runs-on: [arc-runner-set]

    steps:
      - name: Install Git
        run: sudo apt-get update && sudo apt-get install -y git

      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Login to GAR
        uses: docker/login-action@v3
        with:
          registry: us-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.GAR_JSON_KEY }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            us-docker.pkg.dev/evmchain/images/relayer
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=ref,event=tag
            type=sha

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          context: .
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            PACKAGE=relayer
