name: Check links

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - "**/README.md"
  push:
    paths:
      - "**/README.md"

permissions:
  contents: read

concurrency:
  group: check-links-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check-links:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Check links
        uses: lycheeverse/lychee-action@v2
        with:
          args: --no-progress --verbose "**/README.md" --accept '429, 200'
