name: Taikoon UI Build and Checks

on: workflow_call

jobs:
  build:
    runs-on: [arc-runner-set]
    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.12.1
        with:
          access_token: ${{ github.token }}

      - name: Install Git
        run: sudo apt-get update && sudo apt-get install -y git

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install pnpm dependencies
        uses: ./.github/actions/install-pnpm-dependencies
      # This step is needed because the .env file is not committed to the repository
      # and the Svelte check complains about not finding the exports from $env/static/public,
      # which will be generated based on the .env file when running `svelte-kit sync`
      - name: Copy .env.example to .env
        working-directory: ./packages/taikoon-ui
        run: cp .env.example .env

      - name: Frontend build
        working-directory: ./packages/taikoon-ui
        run: pnpm build

      - name: Svelte check
        working-directory: ./packages/taikoon-ui
        run: pnpm check

      - name: Check formatting
        working-directory: ./packages/taikoon-ui
        run: pnpm lint

      - name: Unit tests
        env:
          SKIP_ENV_VALIDATION: "true"
        working-directory: ./packages/taikoon-ui
        run: pnpm test:unit
