name: Hoodi USDC Faucet UI Preview

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths:
      - "packages/usdc-faucet-ui/**"
    branches-ignore:
      - release-please--branches--**

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test:
    if: ${{ github.event.pull_request.draft == false && !startsWith(github.head_ref, 'release-please') && !startsWith(github.head_ref, 'dependabot') }}
    uses: ./.github/workflows/usdc-faucet-ui--ci.yml

  deploy_usdc-faucet-ui_hoodi_preview:
    if: ${{ github.event.pull_request.draft == false && !startsWith(github.head_ref, 'release-please') && github.event.pull_request.head.repo.fork == false && !startsWith(github.head_ref, 'dependabot') }}
    needs: build-and-test
    uses: ./.github/workflows/repo--vercel-deploy.yml
    with:
      environment: "preview"
      flags: ""
    secrets:
      vercel_project_id: ${{ secrets.VERCEL_PROJECT_ID_USDC_FAUCET_UI_HOODI }}
      vercel_org_id: ${{ secrets.VERCEL_ORG_ID }}
      vercel_token: ${{ secrets.VERCEL_TOKEN }}
