name: Hoodi USDC Faucet UI Production

on:
  push:
    tags:
      - "usdc-faucet-ui-hoodi-v*"

jobs:
  deploy_usdc-faucet-ui_hoodi_production:
    uses: ./.github/workflows/repo--vercel-deploy.yml
    with:
      environment: "production"
      flags: "--prod"
    secrets:
      vercel_project_id: ${{ secrets.VERCEL_PROJECT_ID_USDC_FAUCET_UI_HOODI }}
      vercel_org_id: ${{ secrets.VERCEL_ORG_ID }}
      vercel_token: ${{ secrets.VERCEL_TOKEN }}
