# !!!!!!!   DO NOT EDIT THIS FILE   !!!!!!!
# This file is machine-generated by lib/unicore/mktables from the Unicode
# database, Version 14.0.0.  Any changes made here will be lost!

# !!!!!!!   INTERNAL PERL USE ONLY   !!!!!!!
# This file is for internal use by core Perl only.  The format and even the
# name or existence of this file are subject to change without notice.  Don't
# use it directly.  Use Unicode::UCD to access the Unicode character data
# base.


return <<'END';
V44
3387
3389
3642
3643
3662
3663
3770
3771
3972
3973
4154
4155
5908
5910
5940
5941
6097
6098
6778
6779
7082
7083
7154
7156
43052
43053
43347
43348
44013
44014
69744
69745
69940
69941
70378
70379
71467
71468
71997
71998
72244
72245
73028
73029
END
